// opcgpro-vue/src/components/home/LobbyPanel.vue
<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { useStore } from "@/composables/useStore";
import { useNetStore } from "@/store/netStore";
import { loadAllDecks } from "@/data/DeckMapper";
import { HomeRequest } from "@/net/HomeProtocol";
import { showMessage } from "@/components/ui/MessageBox";
import ScreenHead from "@/components/shared/ScreenHead.vue";
import Ticks from "@/components/shared/Ticks.vue";

const emit = defineEmits<{ (e: "goToDeck"): void }>();

const matchState = useStore(useNetStore, (s) => s.matchState);
const selectedDeck = useStore(useNetStore, (s) => s.selectedDeck);
const opponentName = useStore(useNetStore, (s) => s.opponentName);
const roomCode = useStore(useNetStore, (s) => s.roomCode);

const roomMode = ref<"none" | "create" | "join">("none");
const joinInput = ref("");
const copied = ref(false);
const botGoFirst = ref(true);

// ── TEMP: dev-only 测试入口（验证后删除） ─────────────────────────────
onMounted(() => {
  if (typeof window === "undefined") return;
  const url = new URL(window.location.href);
  if (url.searchParams.get("__test") === "bot") {
    const decks = loadAllDecks();
    const firstName = Object.keys(decks)[0];
    if (firstName) {
      const d = decks[firstName];
      useNetStore.getState().setSelectedDeck({
        name: firstName,
        leader: d.leader,
        leaderName: d.leaderName,
        cards: [d.leader, ...d.cards].join("\n"),
      });
    } else {
      useNetStore.getState().setSelectedDeck({
        name: "测试卡组",
        leader: "OP01-001",
        leaderName: "路飞",
        cards: "OP01-001\nOP01-004",
      });
    }
    useNetStore.getState().setOpponentName("机器人对手");
    useNetStore.getState().setMatchState("bot-matching");
  }
});

const leaderSprite = computed(() => {
  if (!selectedDeck.value) return "";
  const decks = loadAllDecks();
  return decks[selectedDeck.value.name]?.leaderSprite ?? "";
});

function handleMatch() {
  if (!selectedDeck.value) return;
  HomeRequest.enterMatch(selectedDeck.value.cards);
}
function handleBotMatch() {
  if (!selectedDeck.value) return;
  const sent = HomeRequest.enterBotMatch(
    selectedDeck.value.cards,
    botGoFirst.value,
  );
  if (!sent) showMessage("服务器未连接，请稍后重试", "error");
}
function handleCancelMatch() {
  HomeRequest.cancelMatch();
}
function handleCreateRoom() {
  if (!selectedDeck.value) return;
  roomMode.value = "create";
  const sent = HomeRequest.createRoom(selectedDeck.value.cards);
  if (!sent) {
    showMessage("服务器未连接，请稍后重试", "error");
    roomMode.value = "none";
  }
}
function handleJoinRoom() {
  if (!selectedDeck.value) return;
  roomMode.value = "join";
}
function confirmJoinRoom() {
  const code = joinInput.value.trim().toUpperCase();
  if (code.length < 6 || !selectedDeck.value) return;
  HomeRequest.joinRoom(code, selectedDeck.value.cards);
  joinInput.value = "";
}
function handleCancelRoom() {
  HomeRequest.cancelRoom();
  roomMode.value = "none";
  joinInput.value = "";
}
function copyRoomCode() {
  if (!roomCode.value) return;
  navigator.clipboard
    .writeText(roomCode.value)
    .then(() => {
      copied.value = true;
      setTimeout(() => (copied.value = false), 2000);
    })
    .catch(() => {});
}
</script>

<template>
  <div class="lobby-root enter scroll">
    <ScreenHead kicker="集结你的船员" title="对战大厅" />

    <!-- ── 当前卡组卡片 ────────────────────────────────────── -->
    <div v-if="selectedDeck" class="panel panel-pad deck-card">
      <Ticks />
      <div class="deck-card__color-block">
        <img
          v-if="leaderSprite"
          :src="leaderSprite"
          class="deck-card__leader-img"
          :alt="selectedDeck.leaderName"
          @error="($event.target as HTMLImageElement).src = '/sprites/CardBack.png'"
        />
        <span v-else class="head">{{ selectedDeck.name.charAt(0) }}</span>
      </div>
      <div class="deck-card__info">
        <span class="mono faint deck-card__eyebrow">当前卡组 · 领航</span>
        <p class="head deck-card__name">{{ selectedDeck.name }}</p>
        <span class="mono dim deck-card__leader"
          >{{ selectedDeck.leaderName }} · 已就绪</span
        >
      </div>
      <button
        class="btn btn--ghost deck-card__change"
        @click="emit('goToDeck')">
        更换 →
      </button>
    </div>

    <div v-else class="panel deck-empty">
      <Ticks />
      <div class="deck-empty__mark">?</div>
      <p class="dim deck-empty__text">尚未选择卡组，请前往卡组页面创建</p>
    </div>

    <!-- ── 操作按钮区（idle） ──────────────────────────────── -->
    <template v-if="matchState === 'idle' && !roomCode && roomMode === 'none'">
      <div class="lobby-actions">
        <button
          class="btn btn--primary btn--lg btn--match"
          :disabled="!selectedDeck"
          @click="handleMatch">
          <span>▶</span> 开始匹配
        </button>

        <div class="bot-group">
          <button
            class="btn"
            :disabled="!selectedDeck"
            title="与机器人对战"
            @click="handleBotMatch">
            单人测试
          </button>
          <div class="seg bot-seg">
            <button
              :class="['seg__opt', { 'is-active': botGoFirst }]"
              @click="botGoFirst = true">
              先手
            </button>
            <button
              :class="['seg__opt', { 'is-active': !botGoFirst }]"
              @click="botGoFirst = false">
              后手
            </button>
          </div>
        </div>
      </div>

      <div class="rule" style="width: 320px; margin: 4px 0">或与好友对战</div>

      <div class="room-actions">
        <button class="btn" :disabled="!selectedDeck" @click="handleCreateRoom">
          <span>＋</span> 创建房间
        </button>
        <button class="btn" :disabled="!selectedDeck" @click="handleJoinRoom">
          <span>→</span> 加入房间
        </button>
      </div>
    </template>

    <!-- ── 匹配中 ───────────────────────────────────────────── -->
    <div
      v-else-if="matchState === 'matching'"
      class="panel panel-pad state-card">
      <Ticks />
      <div class="state-card__ring"><div class="state-card__ring-spin" /></div>
      <p class="kicker state-card__eyebrow">SEARCHING FOR OPPONENT</p>
      <p class="head state-card__title">寻找对手中</p>
      <p class="dim state-card__hint">系统正在为你匹配水平相近的对手</p>
      <button class="btn btn--ghost" @click="handleCancelMatch">
        取消匹配
      </button>
    </div>

    <!-- ── 单人测试开局 ─────────────────────────────────────── -->
    <div
      v-else-if="matchState === 'bot-matching'"
      class="panel panel-pad state-card">
      <Ticks />
      <div class="state-card__ring"><div class="state-card__ring-spin" /></div>
      <p class="kicker state-card__eyebrow">SOLO · INITIALIZING</p>
      <p class="head state-card__title">对手：机器人对手</p>
      <p class="dim state-card__hint">正在初始化对战...</p>
      <button class="btn btn--ghost" @click="handleCancelMatch">取消</button>
    </div>

    <!-- ── 匹配成功 ─────────────────────────────────────────── -->
    <div
      v-else-if="matchState === 'matched'"
      class="panel panel-pad state-card state-card--success">
      <Ticks />
      <div class="state-card__success-icon">✓</div>
      <p class="kicker state-card__eyebrow">MATCH FOUND</p>
      <p class="head state-card__title">对手：{{ opponentName }}</p>
      <p class="dim state-card__hint">即将进入游戏...</p>
    </div>

    <!-- ── 创建房间中 ───────────────────────────────────────── -->
    <div
      v-else-if="!roomCode && roomMode === 'create'"
      class="panel panel-pad state-card">
      <Ticks />
      <div class="state-card__ring"><div class="state-card__ring-spin" /></div>
      <p class="kicker state-card__eyebrow">CREATING ROOM</p>
      <p class="head state-card__title">房间创建中</p>
      <button class="btn btn--ghost" @click="handleCancelRoom">取消</button>
    </div>

    <!-- ── 房间码展示 ───────────────────────────────────────── -->
    <div
      v-else-if="roomCode && roomMode === 'create'"
      class="panel panel-pad state-card">
      <Ticks />
      <p class="kicker state-card__eyebrow">ROOM CODE</p>
      <p
        class="head state-card__room-code"
        :class="{ 'state-card__room-code--copied': copied }">
        {{ roomCode }}
      </p>
      <div class="state-card__actions">
        <button class="btn" @click="copyRoomCode">
          {{ copied ? "✓ 已复制" : "复制房间码" }}
        </button>
        <button class="btn btn--ghost" @click="handleCancelRoom">取消</button>
      </div>
      <p class="dim state-card__hint">等待好友加入...</p>
    </div>

    <!-- ── 加入房间 ─────────────────────────────────────────── -->
    <div
      v-else-if="roomMode === 'join' && !roomCode"
      class="panel panel-pad state-card">
      <Ticks />
      <p class="kicker state-card__eyebrow">ENTER ROOM CODE</p>
      <div class="field state-card__field">
        <span class="ic mono">›</span>
        <input
          :value="joinInput"
          placeholder="000000"
          :maxlength="6"
          @input="
            joinInput = ($event.target as HTMLInputElement).value.toUpperCase()
          "
          @keydown.enter="confirmJoinRoom" />
      </div>
      <div class="state-card__actions">
        <button
          class="btn btn--primary"
          :disabled="joinInput.trim().length < 6"
          @click="confirmJoinRoom">
          加入
        </button>
        <button class="btn btn--ghost" @click="handleCancelRoom">取消</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.lobby-root {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 26px;
  padding: 24px 40px 40px;
  height: 100%;
  overflow-y: auto;
  font-family: var(--font-ui);
}

/* ── 当前卡组卡片 ───────────────────────────────────────── */
.deck-card {
  width: min(560px, 80%);
  display: flex;
  align-items: center;
  gap: 20px;
  padding: 22px;
}
.deck-card__color-block {
  width: 64px;
  height: 90px;
  border-radius: var(--radius);
  background: linear-gradient(160deg, var(--accent), var(--bg1));
  border: 1.5px solid var(--accent);
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-head);
  font-weight: 900;
  font-size: 22px;
  color: #fff;
  flex-shrink: 0;
  overflow: hidden;
}
.deck-card__leader-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: top center;
  display: block;
}
.deck-card__info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.deck-card__eyebrow {
  font-size: 10px;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}
.deck-card__name {
  font-size: 22px;
  margin: 0;
  color: var(--ink);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.deck-card__leader {
  font-size: 12px;
}
.deck-card__change {
  flex-shrink: 0;
}

/* ── 空卡组卡片 ─────────────────────────────────────────── */
.deck-empty {
  width: min(560px, 80%);
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 22px;
}
.deck-empty__mark {
  width: 64px;
  height: 64px;
  border-radius: 50%;
  border: 1.5px dashed var(--line-strong);
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-head);
  font-weight: 900;
  font-size: 28px;
  color: var(--primary);
  box-shadow: 0 0 18px -6px var(--primary-glow);
}
.deck-empty__text {
  margin: 0;
  font-size: 14px;
}

/* ── 操作按钮行 ─────────────────────────────────────────── */
.lobby-actions {
  display: flex;
  align-items: center;
  gap: 16px;
  flex-wrap: wrap;
  justify-content: center;
}
.btn--match {
  min-width: 220px;
  font-size: 18px;
}
.bot-group {
  display: flex;
  align-items: center;
  gap: 10px;
}
.bot-seg {
  height: 48px;
}
.bot-seg .seg__opt {
  padding: 8px 18px;
  font-size: 14px;
}

.room-actions {
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
  justify-content: center;
}

/* ── 状态卡片（匹配中/房间码/输入码） ──────────────────── */
.state-card {
  width: min(480px, 80%);
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 14px;
  padding: 28px;
  text-align: center;
}
.state-card__ring {
  width: 56px;
  height: 56px;
  border: 2px solid var(--line);
  border-top-color: var(--primary);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 0 18px -6px var(--primary-glow);
}
.state-card__ring-spin {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  border: 2px solid transparent;
  border-top-color: var(--primary);
  animation: spin 1.1s linear infinite;
}
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.state-card__eyebrow {
  font-size: 11px;
  letter-spacing: 0.24em;
}
.state-card__title {
  font-size: 26px;
  margin: 0;
  color: var(--ink);
}
.state-card__hint {
  font-size: 13px;
  margin: 0;
}
.state-card__success-icon {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: linear-gradient(180deg, var(--primary-bright), var(--primary));
  color: var(--on-primary);
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-head);
  font-weight: 900;
  font-size: 32px;
  box-shadow: 0 0 24px var(--primary-glow);
}
.state-card--success .state-card__title {
  color: var(--good);
}
.state-card__room-code {
  font-family: var(--font-mono);
  font-size: 38px;
  letter-spacing: 0.4em;
  color: var(--primary);
  margin: 4px 0;
  text-shadow: 0 0 24px var(--primary-glow);
  padding: 6px 18px;
  border: 1px dashed var(--line-strong);
  border-radius: var(--radius);
  background: var(--bg1);
  transition: all 0.3s;
}
.state-card__room-code--copied {
  color: var(--good);
  border-color: var(--good);
  box-shadow: 0 0 18px color-mix(in srgb, var(--good) 50%, transparent);
}
.state-card__field {
  width: 100%;
  max-width: 260px;
  margin-top: 4px;
}
.state-card__actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  justify-content: center;
}
</style>

// opcgpro-web/src/components/home/LobbyPanel.tsx
"use client";

import { useEffect, useState } from "react";
import { useNetStore } from "@/store/netStore";
import { HomeRequest } from "@/net/HomeProtocol";
import { showMessage } from "@/components/ui/MessageBox";
import ChatPanel from "./ChatPanel";
import { advanceImageFallback, CARD_BACK_SRC, thumbSrc } from "@/lib/sprite";

// 从导出卡组码（exportDeckString 格式 A）统计主卡组张数：
// 卡牌行形如「<数量> <卡号>」，跳过「# 注释」与「领航:」行。
// 解析不出（返回 0）时按「未知」处理，调用方 fail-open，避免误拦合法卡组。
function countMainCards(deckStr: string): number {
  let total = 0;
  for (const line of deckStr.split("\n")) {
    const m = line.match(/^\s*(\d+)\s+[A-Za-z]/);
    if (m) total += parseInt(m[1], 10);
  }
  return total;
}

export default function LobbyPanel({ onGoToDeck }: { onGoToDeck: () => void }) {
  const matchState    = useNetStore((s) => s.matchState);
  const selectedDeck  = useNetStore((s) => s.selectedDeck);
  const opponentName  = useNetStore((s) => s.opponentName);
  const playerName    = useNetStore((s) => s.playerName);
  const roomCode      = useNetStore((s) => s.roomCode);
  const roomOperation = useNetStore((s) => s.roomOperation);
  const connState     = useNetStore((s) => s.connState);

  const [roomMode, setRoomMode] = useState<"none" | "create" | "join">("none");
  const [playMode, setPlayMode] = useState<"match" | "friend" | "bot">("match");
  const [joinInput, setJoinInput] = useState("");
  const [copied, setCopied] = useState(false);
  const [botGoFirst, setBotGoFirst] = useState(true);

  // 主卡组须恰好 50 张（后端 DeckValidator 强制，不满会被拒，bug #183）。
  // 这里前置拦截：未满 50 时置灰按钮并提示，避免「点了没反应」。
  // mainCount === 0 表示解析失败/未知，fail-open 不拦截，交由后端校验兜底。
  const mainCount     = selectedDeck ? countMainCards(selectedDeck.cards) : 0;
  const deckIncomplete = mainCount > 0 && mainCount !== 50;
  const canEnter      = !!selectedDeck && !deckIncomplete && connState === "connected" && roomOperation === "idle";

  useEffect(() => {
    if (roomMode === "create" && roomOperation === "idle" && !roomCode) {
      setRoomMode("none");
    }
  }, [roomCode, roomMode, roomOperation]);

  const handleMatch = () => {
    if (!selectedDeck) return;
    const sent = HomeRequest.enterMatch(selectedDeck.cards, selectedDeck.name);
    if (!sent) {
      showMessage("服务器未连接，请稍后重试", "error");
    }
  };

  const handleCancelMatch = () => {
    HomeRequest.cancelMatch();
  };

  // 单人测试：与机器人对战，方便测试单卡效果（机器人轮到自己会自动结束回合）
  const handleBotMatch = () => {
    if (!selectedDeck) return;
    const sent = HomeRequest.enterBotMatch(selectedDeck.cards, botGoFirst, selectedDeck.name);
    if (!sent) {
      showMessage("服务器未连接，请稍后重试", "error");
    }
  };

  const handleCreateRoom = () => {
    if (!selectedDeck) return;
    setRoomMode("create");
    useNetStore.getState().setRoomOperation("creating");
    const sent = HomeRequest.createRoom(selectedDeck.cards, selectedDeck.name);
    if (!sent) {
      showMessage("服务器未连接，请稍后重试", "error");
      useNetStore.getState().setRoomOperation("idle");
      setRoomMode("none");
    }
  };

  const handleJoinRoom = () => {
    if (!selectedDeck) return;
    setRoomMode("join");
  };

  const confirmJoinRoom = () => {
    const code = joinInput.trim().toUpperCase();
    if (code.length < 6 || !selectedDeck) return;
    useNetStore.getState().setRoomOperation("joining");
    const sent = HomeRequest.joinRoom(code, selectedDeck.cards, selectedDeck.name);
    if (!sent) {
      useNetStore.getState().setRoomOperation("idle");
      showMessage("服务器未连接，房间码已保留，请重连后重试", "error");
    }
  };

  const handleCancelRoom = () => {
    HomeRequest.cancelRoom();
    useNetStore.getState().setRoomOperation("idle");
    setRoomMode("none");
    setJoinInput("");
  };

  const copyRoomCode = () => {
    if (!roomCode) return;
    navigator.clipboard.writeText(roomCode).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  };

  const modeLocked = matchState !== "idle" || roomOperation !== "idle" || Boolean(roomCode);
  const entryHint = !selectedDeck
    ? "请先选择一副卡组"
    : deckIncomplete
      ? `卡组需正好 50 张，当前 ${mainCount} 张`
      : connState !== "connected"
        ? "服务器连接恢复后即可开始"
        : "";

  return (
    <div className="flex h-full min-w-0">
      <div className="min-w-0 flex-1 overflow-y-auto px-4 py-5 @[640px]:px-6 @[1024px]:flex @[1024px]:flex-col @[1024px]:items-center @[1024px]:justify-center @[1024px]:px-8 @[1024px]:py-8">
        <div className="mx-auto flex w-full max-w-xl flex-col gap-4 @[1024px]:gap-5">
          <div>
            <h1 className="text-xl font-bold text-white @[1024px]:text-2xl">开始对战</h1>
            <p className="mt-1 text-sm text-gray-500">选择模式，准备好后即可进入牌桌。</p>
          </div>

          <button
            type="button"
            onClick={onGoToDeck}
            className="w-full rounded-2xl border border-gray-800 bg-gray-900 p-4 text-left transition-colors hover:border-orange-700 active:bg-gray-800"
          >
            {selectedDeck ? (
              <div className="flex items-center gap-3">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={thumbSrc(selectedDeck.leaderSprite || CARD_BACK_SRC)}
                  alt={selectedDeck.leaderName}
                  className="h-16 w-11 shrink-0 rounded-lg border border-gray-700 object-cover"
                  onError={(e) => advanceImageFallback(e.currentTarget, [selectedDeck.leaderSprite])}
                />
                <div className="min-w-0 flex-1">
                  <p className="text-sm text-gray-500">当前卡组</p>
                  <p className="mt-0.5 truncate text-base font-bold text-white">{selectedDeck.name}</p>
                  <p className="mt-0.5 truncate text-sm text-gray-500">领航：{selectedDeck.leaderName}</p>
                </div>
                <span className="shrink-0 text-sm font-medium text-orange-300">更换 ›</span>
              </div>
            ) : (
              <div className="flex min-h-16 items-center justify-between gap-3">
                <div>
                  <p className="font-bold text-white">还没有选择卡组</p>
                  <p className="mt-1 text-sm text-gray-500">先准备一副完整的 50 张卡组</p>
                </div>
                <span className="shrink-0 rounded-lg bg-orange-500 px-3 py-2 text-sm font-bold text-white">去选择</span>
              </div>
            )}
          </button>

          {deckIncomplete && (
            <p role="alert" className="rounded-xl border border-red-900/70 bg-red-950/30 px-3 py-2.5 text-sm text-red-300">
              卡组需正好 50 张，当前 {mainCount} 张。请补满后再开始对战。
            </p>
          )}

          <div className="grid grid-cols-3 rounded-xl border border-gray-800 bg-gray-900 p-1" aria-label="对战模式">
            {([
              ["match", "匹配"],
              ["friend", "好友房"],
              ["bot", "单人"],
            ] as const).map(([mode, label]) => (
              <button
                key={mode}
                type="button"
                onClick={() => setPlayMode(mode)}
                disabled={modeLocked && playMode !== mode}
                aria-pressed={playMode === mode}
                className={`min-h-11 rounded-lg px-2 text-sm font-bold transition-colors ${
                  playMode === mode ? "bg-orange-500 text-white" : "text-gray-500 hover:bg-gray-800 hover:text-gray-200 disabled:opacity-40"
                }`}
              >
                {label}
              </button>
            ))}
          </div>

          <section className="rounded-2xl border border-gray-800 bg-gray-900 p-4 @[640px]:p-5">
            {playMode === "match" && (
              <div className="flex flex-col gap-3">
                {matchState === "idle" && (
                  <>
                    <div>
                      <h2 className="font-bold text-white">公开匹配</h2>
                      <p className="mt-1 text-sm leading-5 text-gray-500">系统会自动寻找在线对手。</p>
                    </div>
                    <button
                      type="button"
                      onClick={handleMatch}
                      disabled={!canEnter}
                      className="h-12 w-full rounded-xl bg-orange-500 text-base font-bold text-white transition-colors hover:bg-orange-400 active:bg-orange-600 disabled:cursor-not-allowed disabled:bg-gray-800 disabled:text-gray-600"
                    >
                      开始匹配
                    </button>
                  </>
                )}
                {matchState === "matching" && (
                  <div className="flex flex-col items-center gap-3 py-2" role="status">
                    <div className="h-6 w-6 animate-spin rounded-full border-2 border-orange-500 border-t-transparent" />
                    <p className="font-bold text-orange-300">正在寻找对手…</p>
                    <button type="button" onClick={handleCancelMatch} className="min-h-11 rounded-lg px-4 text-sm text-gray-400 hover:bg-gray-800 hover:text-white">
                      取消匹配
                    </button>
                  </div>
                )}
                {matchState === "matched" && (
                  <div className="py-2 text-center" role="status">
                    <p className="font-bold text-green-400">匹配成功</p>
                    <p className="mt-2 text-sm text-gray-300">对手：<strong className="text-white">{opponentName}</strong></p>
                    <p className="mt-1 text-sm text-gray-500">正在进入牌桌…</p>
                  </div>
                )}
              </div>
            )}

            {playMode === "bot" && (
              <div className="flex flex-col gap-4">
                <div>
                  <h2 className="font-bold text-white">单人测试</h2>
                  <p className="mt-1 text-sm leading-5 text-gray-500">与机器人对战，适合测试卡组与单卡效果。</p>
                </div>
                <div>
                  <p className="mb-2 text-sm text-gray-400">选择顺序</p>
                  <div className="grid grid-cols-2 rounded-xl border border-sky-800 p-1">
                    <button type="button" onClick={() => setBotGoFirst(true)} aria-pressed={botGoFirst} className={`min-h-11 rounded-lg text-sm font-bold ${botGoFirst ? "bg-sky-600 text-white" : "text-gray-400"}`}>先手</button>
                    <button type="button" onClick={() => setBotGoFirst(false)} aria-pressed={!botGoFirst} className={`min-h-11 rounded-lg text-sm font-bold ${!botGoFirst ? "bg-sky-600 text-white" : "text-gray-400"}`}>后手</button>
                  </div>
                </div>
                <button type="button" onClick={handleBotMatch} disabled={!canEnter} className="h-12 w-full rounded-xl bg-sky-600 text-base font-bold text-white hover:bg-sky-500 disabled:cursor-not-allowed disabled:bg-gray-800 disabled:text-gray-600">
                  开始单人测试
                </button>
              </div>
            )}

            {playMode === "friend" && (
              <div className="flex flex-col gap-4">
                {roomMode === "none" && !roomCode && (
                  <>
                    <div>
                      <h2 className="font-bold text-white">好友房</h2>
                      <p className="mt-1 text-sm leading-5 text-gray-500">创建房间码，或输入好友发来的房间码。</p>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      <button type="button" onClick={handleCreateRoom} disabled={!canEnter} className="min-h-12 rounded-xl bg-blue-600 px-3 text-sm font-bold text-white hover:bg-blue-500 disabled:cursor-not-allowed disabled:bg-gray-800 disabled:text-gray-600">创建房间</button>
                      <button type="button" onClick={handleJoinRoom} disabled={!canEnter} className="min-h-12 rounded-xl bg-green-600 px-3 text-sm font-bold text-white hover:bg-green-500 disabled:cursor-not-allowed disabled:bg-gray-800 disabled:text-gray-600">加入房间</button>
                    </div>
                  </>
                )}

                {!roomCode && roomMode === "create" && roomOperation === "creating" && (
                  <div className="flex flex-col items-center gap-3 py-2" role="status">
                    <div className="h-6 w-6 animate-spin rounded-full border-2 border-blue-500 border-t-transparent" />
                    <p className="font-bold text-blue-300">正在创建房间…</p>
                    <button type="button" onClick={handleCancelRoom} className="min-h-11 rounded-lg px-4 text-sm text-gray-400 hover:bg-gray-800 hover:text-white">取消</button>
                  </div>
                )}

                {roomCode && roomMode === "create" && (
                  <div className="flex flex-col items-center gap-3 py-1" role="status">
                    <p className="text-sm text-gray-400">把房间码发给好友</p>
                    <p className="select-all font-mono text-3xl font-black tracking-[0.24em] text-blue-300">{roomCode}</p>
                    <div className="grid w-full grid-cols-2 gap-3">
                      <button type="button" onClick={copyRoomCode} className="min-h-11 rounded-xl bg-blue-600 px-3 text-sm font-bold text-white hover:bg-blue-500">{copied ? "已复制" : "复制房间码"}</button>
                      <button type="button" onClick={handleCancelRoom} className="min-h-11 rounded-xl bg-gray-800 px-3 text-sm text-gray-300 hover:bg-gray-700">取消房间</button>
                    </div>
                    <p className="text-sm text-gray-500">等待对手加入…</p>
                  </div>
                )}

                {roomMode === "join" && !roomCode && (
                  <div className="flex flex-col gap-3">
                    <label htmlFor="join-room-code" className="text-sm font-medium text-gray-300">房间码</label>
                    <input
                      id="join-room-code"
                      value={joinInput}
                      onChange={(e) => setJoinInput(e.target.value.toUpperCase())}
                      placeholder="输入 6 位房间码"
                      maxLength={6}
                      autoCapitalize="characters"
                      className="h-12 w-full rounded-xl border border-gray-700 bg-gray-800 px-3 text-center font-mono text-lg tracking-[0.2em] text-white outline-none focus:border-green-500"
                      onKeyDown={(e) => e.key === "Enter" && confirmJoinRoom()}
                    />
                    <div className="grid grid-cols-2 gap-3">
                      <button type="button" onClick={handleCancelRoom} className="min-h-11 rounded-xl bg-gray-800 px-3 text-sm text-gray-300 hover:bg-gray-700">取消</button>
                      <button
                        type="button"
                        onClick={confirmJoinRoom}
                        disabled={joinInput.trim().length < 6 || roomOperation === "joining" || connState !== "connected"}
                        className="min-h-11 rounded-xl bg-green-600 px-3 text-sm font-bold text-white hover:bg-green-500 disabled:cursor-not-allowed disabled:bg-gray-800 disabled:text-gray-600"
                      >
                        {roomOperation === "joining" ? "正在加入…" : "加入房间"}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}
          </section>

          {entryHint && matchState === "idle" && roomOperation === "idle" && (
            <p className="pb-2 text-center text-sm text-gray-500">{entryHint}</p>
          )}
        </div>
      </div>

      <div className="hidden w-72 shrink-0 border-l border-gray-800 @[1024px]:block">
        <ChatPanel />
      </div>
    </div>
  );
}
