// opcgpro-web/src/components/deck-editor/SearchPanel.tsx
"use client";

import { useState } from "react";
import { useDeckStore } from "@/store/deckStore";
import {
  COLOR_DISPLAY_NAMES,
  COLOR_DISPLAY_TO_DATA,
  COLOR_DATA_TO_DISPLAY,
  COLOR_STYLES,
} from "@/lib/colorMap";

const PROPERTIES = ["", "斩", "打", "射", "智", "特"];
const DECK_TYPES  = ["", "Character", "Stage", "Event"];

const TYPE_LABELS: Record<string, string> = {
  Character: "角色", Stage: "场地", Event: "事件",
};
const RARITIES    = ["", "L", "SR", "R", "UC", "C", "SEC", "P"];
const COL_PRESETS = [4, 5, 6, 7, 8, 9, 10, 12];


// 按弹数筛选用的卡集列表（与 cardSets.ts 同步；新卡集发售时手动追加）
const SET_GROUPS: { label: string; sets: string[] }[] = [
  { label: "OP 主弹", sets: ["OP01","OP02","OP03","OP04","OP05","OP06","OP07","OP08","OP09","OP10","OP11","OP12","OP13","OP14","OP15","OP16"] },
  { label: "ST 起始", sets: ["ST01","ST02","ST03","ST04","ST05","ST06","ST07","ST08","ST09","ST10","ST11","ST12","ST13","ST14","ST15","ST16","ST17","ST18","ST19","ST20","ST21","ST22","ST23","ST24","ST25","ST26","ST27","ST28","ST29","ST30"] },
  { label: "EB/PRB", sets: ["EB01","EB02","EB03","EB04","PRB01","PRB02"] },
  { label: "P/其他", sets: ["P","OPD","TY01"] },
];

export default function SearchPanel() {
  const {
    searchQuery, filterColor, filterType, filterProperty, filterRarity,
    filterSets, filterShowSub1,
    gridColumns,
    setSearchQuery, setFilterColor, setFilterType, setFilterProperty, setFilterRarity,
    toggleFilterSet, clearFilterSets, setFilterShowSub1,
    setGridColumns,
  } = useDeckStore();

  const [showSettings, setShowSettings] = useState(false);
  const [setGroupExpanded, setSetGroupExpanded] = useState<number | null>(null);

  const isLeaderMode        = filterType === "Leader";
  const activeDisplayColor  = COLOR_DATA_TO_DISPLAY[filterColor] ?? "";
  const hasFilter           = !!(searchQuery || filterColor || filterType || filterProperty || filterRarity || filterSets.length > 0 || filterShowSub1);

  return (
    <div className="flex flex-col h-full">
      {/* 标题 */}
      <div className="px-3 pt-3 pb-2 border-b border-gray-800 shrink-0">
        <h2 className="text-white font-bold text-sm">搜索卡牌</h2>
      </div>

      {/* 筛选区（可滚动） */}
      <div className="flex-1 overflow-y-auto">
        <div className="flex flex-col gap-3 p-3">
          {/* 搜索框 */}
          <input
            className="w-full bg-gray-800 text-white text-xs rounded-lg px-2.5 py-2 outline-none border border-gray-700 focus:border-orange-500 transition-colors"
            placeholder="卡名 / 关键词 / 效果..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />

          {/* 领航卡切换 */}
          <button
            onClick={() => setFilterType(isLeaderMode ? "" : "Leader")}
            className={`w-full py-1.5 rounded-lg text-xs font-bold transition-colors border ${
              isLeaderMode
                ? "bg-yellow-500 text-black border-yellow-400"
                : "bg-gray-800 text-gray-400 border-gray-700 hover:text-white"
            }`}
          >
            {isLeaderMode ? "✦ 领航模式（退出）" : "选择领航卡"}
          </button>

          {/* 普通类型 */}
          {!isLeaderMode && (
            <div className="flex flex-col gap-1">
              <label className="text-gray-500 text-[10px]">类型</label>
              <div className="flex flex-wrap gap-1">
                {DECK_TYPES.map((t) => (
                  <button key={t} onClick={() => setFilterType(t)}
                    className={`px-2 py-0.5 rounded text-[10px] transition-colors ${
                      filterType === t
                        ? "bg-orange-500 text-white"
                        : "bg-gray-800 text-gray-400 hover:text-white"
                    }`}>
                    {t ? TYPE_LABELS[t] ?? t : "全部"}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* 颜色 */}
          <div className="flex flex-col gap-1">
            <label className="text-gray-500 text-[10px]">颜色</label>
            <div className="flex flex-wrap gap-1">
              <button onClick={() => setFilterColor("")}
                className={`px-2 py-0.5 rounded text-[10px] transition-colors ${
                  filterColor === ""
                    ? "bg-orange-500 text-white"
                    : "bg-gray-800 text-gray-400 hover:text-white"
                }`}>
                全部
              </button>
              {COLOR_DISPLAY_NAMES.map((name) => {
                const dataValue = COLOR_DISPLAY_TO_DATA[name];
                const styles    = COLOR_STYLES[name];
                const isActive  = activeDisplayColor === name;
                return (
                  <button key={name} onClick={() => setFilterColor(dataValue)}
                    className={`px-2 py-0.5 rounded text-[10px] font-bold transition-all ${
                      isActive
                        ? `${styles.bg} text-white scale-105`
                        : `bg-gray-800 ${styles.text} hover:scale-105`
                    }`}>
                    {name}
                  </button>
                );
              })}
            </div>
          </div>

          {/* 属性 */}
          <div className="flex flex-col gap-1">
            <label className="text-gray-500 text-[10px]">属性</label>
            <div className="flex flex-wrap gap-1">
              {PROPERTIES.map((p) => (
                <button key={p} onClick={() => setFilterProperty(p)}
                  className={`px-2 py-0.5 rounded text-[10px] transition-colors ${
                    filterProperty === p
                      ? "bg-orange-500 text-white"
                      : "bg-gray-800 text-gray-400 hover:text-white"
                  }`}>
                  {p || "全部"}
                </button>
              ))}
            </div>
          </div>

          {/* 稀有度 */}
          <div className="flex flex-col gap-1">
            <label className="text-gray-500 text-[10px]">稀有度</label>
            <div className="flex flex-wrap gap-1">
              {RARITIES.map((r) => (
                <button key={r} onClick={() => {
                  setFilterRarity(r);
                  if (r === "L") setFilterType("Leader");
                }}
                  className={`px-2 py-0.5 rounded text-[10px] transition-colors ${
                    filterRarity === r
                      ? "bg-orange-500 text-white"
                      : "bg-gray-800 text-gray-400 hover:text-white"
                  }`}>
                  {r || "全部"}
                </button>
              ))}
            </div>
          </div>

          {/* 弹数筛选（按组展开，多选） */}
          <div className="flex flex-col gap-1">
            <div className="flex items-center justify-between">
              <label className="text-gray-500 text-[10px]">弹数</label>
              {filterSets.length > 0 && (
                <button onClick={clearFilterSets}
                  className="text-gray-600 hover:text-orange-400 text-[9px]">清空</button>
              )}
            </div>
            <div className="flex flex-col gap-1">
              {SET_GROUPS.map((g, gi) => {
                const isOpen = setGroupExpanded === gi;
                const selectedInGroup = g.sets.filter((s) => filterSets.includes(s)).length;
                return (
                  <div key={g.label} className="flex flex-col gap-1">
                    <button
                      onClick={() => setSetGroupExpanded(isOpen ? null : gi)}
                      className={`w-full text-left px-2 py-1 rounded text-[10px] font-bold transition-colors flex items-center justify-between ${
                        selectedInGroup > 0
                          ? "bg-gray-800 text-orange-300"
                          : "bg-gray-800 text-gray-400 hover:text-white"
                      }`}>
                      <span>{g.label} {selectedInGroup > 0 && `(${selectedInGroup})`}</span>
                      <span className="text-gray-600">{isOpen ? "▾" : "▸"}</span>
                    </button>
                    {isOpen && (
                      <div className="flex flex-wrap gap-0.5 pl-1">
                        {g.sets.map((s) => (
                          <button key={s} onClick={() => toggleFilterSet(s)}
                            className={`px-1.5 py-0.5 rounded text-[9px] font-bold transition-colors ${
                              filterSets.includes(s)
                                ? "bg-orange-500 text-white"
                                : "bg-gray-700 text-gray-400 hover:text-white"
                            }`}>
                            {s}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* 角标=1 切换（默认隐藏，按下显示） */}
          <button
            onClick={() => setFilterShowSub1(!filterShowSub1)}
            className={`w-full py-1.5 rounded-lg text-[10px] font-bold transition-colors border ${
              filterShowSub1
                ? "bg-blue-600/40 text-blue-200 border-blue-600"
                : "bg-gray-800 text-gray-500 border-gray-700 hover:text-white"
            }`}
            title="角标=1 通常是旧环境/早期版本卡，默认隐藏"
          >
            {filterShowSub1 ? "✓ 显示角标 1 卡" : "已隐藏角标 1 卡"}
          </button>

          {/* 清除筛选 */}
          {hasFilter && (
            <button
              onClick={() => {
                setSearchQuery(""); setFilterColor(""); setFilterType(""); setFilterProperty(""); setFilterRarity("");
                clearFilterSets(); setFilterShowSub1(false);
              }}
              className="text-gray-600 hover:text-white text-[10px] transition-colors text-center"
            >
              清除筛选
            </button>
          )}
        </div>
      </div>

      {/* 底部设置区 */}
      <div className="border-t border-gray-800 shrink-0">
        {/* 设置面板（展开时显示在按钮上方） */}
        {showSettings && (
          <div className="px-3 py-2.5 bg-gray-900 border-b border-gray-800">
            <p className="text-gray-400 text-[10px] mb-2">每行卡牌数</p>

            {/* 快捷预设 */}
            <div className="flex flex-wrap gap-1 mb-2">
              {COL_PRESETS.map((n) => (
                <button key={n} onClick={() => setGridColumns(n)}
                  className={`w-7 h-6 rounded text-[10px] font-bold transition-colors ${
                    gridColumns === n
                      ? "bg-orange-500 text-white"
                      : "bg-gray-800 text-gray-400 hover:text-white"
                  }`}>
                  {n}
                </button>
              ))}
            </div>

            {/* 微调 +/- */}
            <div className="flex items-center gap-2">
              <button onClick={() => setGridColumns(gridColumns - 1)}
                disabled={gridColumns <= 4}
                className="w-7 h-7 rounded bg-gray-800 text-white text-base font-bold disabled:opacity-30 hover:bg-gray-700 transition-colors">
                −
              </button>
              <span className="flex-1 text-center text-white font-bold text-sm">
                {gridColumns} 列
              </span>
              <button onClick={() => setGridColumns(gridColumns + 1)}
                disabled={gridColumns >= 16}
                className="w-7 h-7 rounded bg-gray-800 text-white text-base font-bold disabled:opacity-30 hover:bg-gray-700 transition-colors">
                +
              </button>
            </div>
          </div>
        )}

        {/* 设置按钮 */}
        <button
          onClick={() => setShowSettings((s) => !s)}
          className={`w-full flex items-center gap-1.5 px-3 py-2 text-[10px] transition-colors ${
            showSettings
              ? "text-orange-400 bg-gray-900"
              : "text-gray-500 hover:text-white hover:bg-gray-900"
          }`}
        >
          <span className="text-xs">⚙</span>
          <span>显示设置</span>
          <span className="ml-auto text-gray-600">{gridColumns} 列</span>
        </button>
      </div>
    </div>
  );
}

// opcgpro-vue/src/components/deck-editor/SearchPanel.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { useStore } from "@/composables/useStore";
import { useDeckStore } from "@/store/deckStore";
import HearthButton from "@/components/ui/HearthButton.vue";
import GoldDivider from "@/components/ui/GoldDivider.vue";
import {
  COLOR_DISPLAY_NAMES,
  COLOR_DISPLAY_TO_DATA,
  COLOR_DATA_TO_DISPLAY,
  COLOR_STYLES,
} from "@/lib/colorMap";

const PROPERTIES = ["", "斩", "打", "射", "智", "特"];
const DECK_TYPES = ["", "Character", "Stage", "Event"];
const TYPE_LABELS: Record<string, string> = { Character: "角色", Stage: "场地", Event: "事件" };
const RARITIES = ["", "L", "SR", "R", "UC", "C", "SEC", "P"];
const COL_PRESETS = [4, 5, 6, 7, 8, 9, 10, 12];

const SET_GROUPS: { label: string; sets: string[] }[] = [
  { label: "OP 主弹", sets: ["OP01","OP02","OP03","OP04","OP05","OP06","OP07","OP08","OP09","OP10","OP11","OP12","OP13","OP14","OP15","OP16"] },
  { label: "ST 起始", sets: ["ST01","ST02","ST03","ST04","ST05","ST06","ST07","ST08","ST09","ST10","ST11","ST12","ST13","ST14","ST15","ST16","ST17","ST18","ST19","ST20","ST21","ST22","ST23","ST24","ST25","ST26","ST27","ST28","ST29","ST30"] },
  { label: "EB/PRB", sets: ["EB01","EB02","EB03","EB04","PRB01","PRB02"] },
  { label: "P/其他", sets: ["P","OPD","TY01"] },
];

const searchQuery = useStore(useDeckStore, (s) => s.searchQuery);
const filterColor = useStore(useDeckStore, (s) => s.filterColor);
const filterType = useStore(useDeckStore, (s) => s.filterType);
const filterProperty = useStore(useDeckStore, (s) => s.filterProperty);
const filterRarity = useStore(useDeckStore, (s) => s.filterRarity);
const filterSets = useStore(useDeckStore, (s) => s.filterSets);
const filterShowSub1 = useStore(useDeckStore, (s) => s.filterShowSub1);
const gridColumns = useStore(useDeckStore, (s) => s.gridColumns);

const store = () => useDeckStore.getState();

let searchDebounce: ReturnType<typeof setTimeout> | null = null;
function onSearchInput(val: string) {
  if (searchDebounce) clearTimeout(searchDebounce);
  searchDebounce = setTimeout(() => store().setSearchQuery(val), 150);
}

const showSettings = ref(false);
const setGroupExpanded = ref<number | null>(null);

const isLeaderMode = computed(() => filterType.value === "Leader");
const activeDisplayColor = computed(() => COLOR_DATA_TO_DISPLAY[filterColor.value] ?? "");
const hasFilter = computed(
  () => !!(searchQuery.value || filterColor.value || filterType.value || filterProperty.value || filterRarity.value || filterSets.value.length > 0 || filterShowSub1.value),
);

function clearAll() {
  const s = store();
  s.setSearchQuery(""); s.setFilterColor(""); s.setFilterType(""); s.setFilterProperty(""); s.setFilterRarity("");
  s.clearFilterSets(); s.setFilterShowSub1(false);
}
function onRarity(r: string) {
  store().setFilterRarity(r);
  if (r === "L") store().setFilterType("Leader");
}
</script>

<template>
  <div class="flex h-full flex-col">
    <div class="shrink-0 border-b border-[var(--line)] bg-[var(--bg0)] px-3 pb-2 pt-3">
      <h2 class="gde-kicker">搜索卡牌</h2>
    </div>

    <div class="flex-1 overflow-y-auto">
      <div class="flex flex-col gap-3 p-3">
        <input
          :value="searchQuery"
          class="w-full rounded-[10px] border border-[var(--line)] bg-[var(--bg1)] px-3 py-2.5 text-xs text-[var(--ink)] outline-none transition-all placeholder:text-[var(--ink-faint)] focus:border-[var(--primary)] focus:shadow-[0_0_0_3px_var(--primary-glow)]"
          placeholder="卡名 / 关键词 / 效果..."
          @input="onSearchInput(($event.target as HTMLInputElement).value)"
        />

        <HearthButton
          :variant="isLeaderMode ? 'primary' : 'secondary'"
          size="md"
          class="w-full"
          @click="store().setFilterType(isLeaderMode ? '' : 'Leader')"
        >
          {{ isLeaderMode ? "✦ 领航模式（退出）" : "选择领航卡" }}
        </HearthButton>

        <GoldDivider spacing="tight" />

        <div v-if="!isLeaderMode" class="flex flex-col gap-1">
          <label class="gde-kicker text-[11px]">类型</label>
          <div class="flex flex-wrap gap-1">
            <button
              v-for="t in DECK_TYPES"
              :key="t"
              :class="[
                'rounded-full border px-2.5 py-0.5 text-[11px] font-mono uppercase tracking-[0.06em] transition-all',
                filterType === t
                  ? 'border-[var(--primary)] bg-[var(--primary)]/15 text-[var(--primary)]'
                  : 'border-[var(--line)] bg-transparent text-[var(--ink-dim)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
              ]"
              @click="store().setFilterType(t)"
            >
              {{ t ? TYPE_LABELS[t] ?? t : "全部" }}
            </button>
          </div>
        </div>

        <div class="flex flex-col gap-1">
          <label class="gde-kicker text-[11px]">颜色</label>
          <div class="flex flex-wrap gap-1">
            <button
              :class="[
                'rounded-full border px-2.5 py-0.5 text-[11px] font-mono uppercase tracking-[0.06em] transition-all',
                filterColor === ''
                  ? 'border-[var(--primary)] bg-[var(--primary)]/15 text-[var(--primary)]'
                  : 'border-[var(--line)] bg-transparent text-[var(--ink-dim)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
              ]"
              @click="store().setFilterColor('')"
            >
              全部
            </button>
            <button
              v-for="name in COLOR_DISPLAY_NAMES"
              :key="name"
              :class="[
                'rounded border px-2 py-0.5 text-xs font-bold transition-all',
                activeDisplayColor === name
                  ? `${COLOR_STYLES[name].bg} scale-105 border-[var(--primary)] text-white shadow-[0_0_8px_var(--primary-glow)]`
                  : `bg-[var(--surface)] ${COLOR_STYLES[name].text} border-[var(--line)] hover:scale-105 hover:border-[var(--line-strong)]`,
              ]"
              @click="store().setFilterColor(COLOR_DISPLAY_TO_DATA[name])"
            >
              {{ name }}
            </button>
          </div>
        </div>

        <div class="flex flex-col gap-1">
          <label class="gde-kicker text-[11px]">属性</label>
          <div class="flex flex-wrap gap-1">
            <button
              v-for="p in PROPERTIES"
              :key="p"
              :class="[
                'rounded-full border px-2.5 py-0.5 text-[11px] font-mono uppercase tracking-[0.06em] transition-all',
                filterProperty === p
                  ? 'border-[var(--primary)] bg-[var(--primary)]/15 text-[var(--primary)]'
                  : 'border-[var(--line)] bg-transparent text-[var(--ink-dim)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
              ]"
              @click="store().setFilterProperty(p)"
            >
              {{ p || "全部" }}
            </button>
          </div>
        </div>

        <div class="flex flex-col gap-1">
          <label class="gde-kicker text-[11px]">稀有度</label>
          <div class="flex flex-wrap gap-1">
            <button
              v-for="r in RARITIES"
              :key="r"
              :class="[
                'rounded-full border px-2.5 py-0.5 text-[11px] font-mono uppercase tracking-[0.06em] transition-all',
                filterRarity === r
                  ? 'border-[var(--primary)] bg-[var(--primary)]/15 text-[var(--primary)]'
                  : 'border-[var(--line)] bg-transparent text-[var(--ink-dim)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
              ]"
              @click="onRarity(r)"
            >
              {{ r || "全部" }}
            </button>
          </div>
        </div>

        <div class="flex flex-col gap-1">
          <div class="flex items-center justify-between">
            <label class="gde-kicker text-[11px]">弹数</label>
            <button v-if="filterSets.length > 0" class="text-[11px] text-[var(--ink-faint)] transition-colors hover:text-[var(--primary)]" @click="store().clearFilterSets()">
              清空
            </button>
          </div>
          <div class="flex flex-col gap-1">
            <div v-for="(g, gi) in SET_GROUPS" :key="g.label" class="flex flex-col gap-1">
              <button
                :class="[
                  'flex w-full items-center justify-between rounded border px-2 py-1 text-left text-xs font-bold transition-colors',
                  g.sets.filter((s) => filterSets.includes(s)).length > 0
                    ? 'border-[var(--primary)]/40 bg-[var(--surface2)]/60 text-[var(--primary)]'
                    : 'border-[var(--line)] bg-transparent text-[var(--ink-dim)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
                ]"
                @click="setGroupExpanded = setGroupExpanded === gi ? null : gi"
              >
                <span>
                  {{ g.label }}
                  <template v-if="g.sets.filter((s) => filterSets.includes(s)).length > 0">
                    ({{ g.sets.filter((s) => filterSets.includes(s)).length }})
                  </template>
                </span>
                <span class="text-[var(--ink-faint)]">{{ setGroupExpanded === gi ? "▾" : "▸" }}</span>
              </button>
              <div v-if="setGroupExpanded === gi" class="flex flex-wrap gap-0.5 pl-1">
                <button
                  v-for="s in g.sets"
                  :key="s"
                  :class="[
                    'rounded-full border px-1.5 py-0.5 text-[11px] font-mono transition-all',
                    filterSets.includes(s)
                      ? 'border-[var(--primary)] bg-[var(--primary)]/20 text-[var(--primary)]'
                      : 'border-[var(--line)] bg-transparent text-[var(--ink-dim)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
                  ]"
                  @click="store().toggleFilterSet(s)"
                >
                  {{ s }}
                </button>
              </div>
            </div>
          </div>
        </div>

        <button
          :class="[
            'w-full rounded border py-1.5 text-xs font-bold transition-all',
            filterShowSub1
              ? 'border-sky-500 bg-sky-500/15 text-sky-300 shadow-[inset_0_0_0_1px_rgba(56,189,248,0.3)]'
              : 'border-[var(--line)] bg-transparent text-[var(--ink-faint)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
          ]"
          title="角标=1 通常是旧环境/早期版本卡，默认隐藏"
          @click="store().setFilterShowSub1(!filterShowSub1)"
        >
          {{ filterShowSub1 ? "✓ 显示角标 1 卡" : "已隐藏角标 1 卡" }}
        </button>

        <button v-if="hasFilter" class="text-center text-xs text-[var(--ink-faint)] transition-colors hover:text-[var(--primary)]" @click="clearAll">
          清除筛选
        </button>
      </div>
    </div>

    <div class="shrink-0 border-t border-[var(--line)]">
      <div v-if="showSettings" class="border-b border-[var(--line)] bg-[var(--surface)]/50 px-3 py-2.5">
        <p class="gde-kicker mb-2 text-[11px]">每行卡牌数</p>
        <div class="mb-2 flex flex-wrap gap-1">
          <button
            v-for="n in COL_PRESETS"
            :key="n"
            :class="[
              'h-6 w-7 rounded border text-xs font-mono font-bold transition-all',
              gridColumns === n
                ? 'border-[var(--primary)] bg-[var(--primary)]/15 text-[var(--primary)]'
                : 'border-[var(--line)] bg-transparent text-[var(--ink-dim)] hover:border-[var(--line-strong)] hover:text-[var(--ink)]',
            ]"
            @click="store().setGridColumns(n)"
          >
            {{ n }}
          </button>
        </div>
        <div class="flex items-center gap-2">
          <button
            :disabled="gridColumns <= 4"
            class="h-7 w-7 rounded border border-[var(--line)] bg-[var(--surface)] text-base font-bold text-[var(--ink)] transition-colors hover:border-[var(--primary)] disabled:opacity-30"
            @click="store().setGridColumns(gridColumns - 1)"
          >
            −
          </button>
          <span class="flex-1 text-center text-sm font-bold text-[var(--ink)]">{{ gridColumns }} 列</span>
          <button
            :disabled="gridColumns >= 16"
            class="h-7 w-7 rounded border border-[var(--line)] bg-[var(--surface)] text-base font-bold text-[var(--ink)] transition-colors hover:border-[var(--primary)] disabled:opacity-30"
            @click="store().setGridColumns(gridColumns + 1)"
          >
            +
          </button>
        </div>
      </div>

      <button
        :class="[
          'flex w-full items-center gap-1.5 px-3 py-2 text-xs transition-all',
          showSettings
            ? 'border-t border-[var(--primary)]/40 bg-[var(--surface)] text-[var(--primary)]'
            : 'text-[var(--ink-faint)] hover:bg-[var(--surface)]/50 hover:text-[var(--ink)]',
        ]"
        @click="showSettings = !showSettings"
      >
        <span class="text-xs">⚙</span>
        <span>显示设置</span>
        <span class="ml-auto text-[var(--ink-faint)]">{{ gridColumns }} 列</span>
      </button>
    </div>
  </div>
</template>
