// opcgpro-web/src/components/game/CardInfoPanel.tsx
"use client";

import type { CardData } from "@/types/card";
import Modal from "@/components/ui/Modal";
import { toDisplayColor, primaryDisplayColor, COLOR_STYLES } from "@/lib/colorMap";

interface Props {
  card: CardData | null;
  onClose: () => void;
}

const TYPE_LABELS: Record<string, string> = {
  Leader:    "领航",
  Character: "角色",
  Stage:     "舞台",
  Event:     "事件",
};

export default function CardInfoPanel({ card, onClose }: Props) {
  if (!card) return null;

  const displayColor = toDisplayColor(card.color);
  const primary      = primaryDisplayColor(card.color);
  const colorStyle   = COLOR_STYLES[primary];

  return (
    <Modal open={!!card} onClose={onClose} title={card.name}>
      <div className="flex gap-4">
        {/* 卡图 */}
        <div className="w-32 h-44 rounded-lg overflow-hidden shrink-0 bg-gray-800 relative">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={card.sprite ?? "/sprites/CardBack.png"}
            alt={card.name}
            className="w-full h-full object-cover"
            onError={(e) => { (e.target as HTMLImageElement).src = "/sprites/CardBack.png"; }}
          />
          {/* 颜色条 */}
          {colorStyle && (
            <div className={`absolute bottom-0 left-0 right-0 h-1 ${colorStyle.bg}`} />
          )}
        </div>

        {/* 卡片信息 */}
        <div className="flex flex-col gap-2 text-sm min-w-0">
          {/* 编号 + 颜色 + 类型 */}
          <div className="flex flex-wrap gap-1.5 items-center">
            <span className="text-orange-400 font-bold text-xs">{card.number}</span>
            <span className={`text-xs font-bold px-1.5 py-0.5 rounded ${colorStyle?.bg ?? "bg-gray-700"} text-white`}>
              {displayColor}
            </span>
            <span className="text-gray-400 text-xs">
              {TYPE_LABELS[card.type] ?? card.type}
            </span>
          </div>

          {/* 稀有度 + 角标 */}
          <div className="flex flex-wrap gap-1.5 items-center">
            {card.rarity && (
              <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${
                card.rarity === 'L'   ? 'bg-yellow-500 text-black' :
                card.rarity === 'SR'  ? 'bg-pink-500 text-white' :
                card.rarity === 'R'   ? 'bg-sky-500 text-white' :
                card.rarity === 'UC'  ? 'bg-gray-500 text-white' :
                card.rarity === 'U'   ? 'bg-gray-500 text-white' :
                card.rarity === 'C'   ? 'bg-gray-700 text-gray-300' :
                card.rarity === 'SEC' ? 'bg-red-600 text-white' :
                card.rarity === 'P'   ? 'bg-emerald-500 text-white' :
                'bg-gray-700 text-white'
              }`}>
                {card.rarity === 'L' ? '领袖' :
                 card.rarity === 'SR' ? '超稀有' :
                 card.rarity === 'R' ? '稀有' :
                 card.rarity === 'UC' ? '罕见' :
                card.rarity === 'U' ? '罕见' :
                 card.rarity === 'C' ? '普通' :
                 card.rarity === 'SEC' ? '隐藏稀有' :
                 card.rarity === 'P' ? '宣传' : card.rarity}
              </span>
            )}
            {card.subscript > 0 && (
              <span className="text-yellow-400 text-xs font-bold">角标 {card.subscript}</span>
            )}
          </div>

          {/* 属性 */}
          {card.property && (
            <p className="text-gray-400 text-xs">
              属性 <span className="text-white">{card.property}</span>
            </p>
          )}

          {/* 威力 */}
          {card.power > 0 && (
            <p className="text-xs">
              <span className="text-gray-400 mr-1">威力</span>
              <span className="text-white font-bold">{card.power.toLocaleString()}</span>
            </p>
          )}

          {/* 费用 */}
          {card.cost > 0 && (
            <p className="text-xs">
              <span className="text-gray-400 mr-1">费用</span>
              <span className="text-white font-bold">{card.cost}</span>
            </p>
          )}

          {/* 反击 */}
          {card.counter > 0 && (
            <p className="text-xs">
              <span className="text-gray-400 mr-1">反击</span>
              <span className="text-white font-bold">+{card.counter}</span>
            </p>
          )}

          {/* 关键词 */}
          {card.keyWords.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {card.keyWords.map((k) => (
                <span key={k} className="text-[10px] bg-blue-900/60 text-blue-300 px-1.5 py-0.5 rounded">
                  {k}
                </span>
              ))}
            </div>
          )}

          {/* 效果文本 */}
          {card.effectText && (
            <p className="text-gray-300 text-[11px] leading-relaxed max-w-52">
              {card.effectText}
            </p>
          )}
        </div>
      </div>
    </Modal>
  );
}

// opcgpro-vue/src/components/game/CardInfoPanel.vue
<script setup lang="ts">
import { computed } from "vue";
import type { CardData } from "@/types/card";
import Modal from "@/components/ui/Modal.vue";
import { toDisplayColor, primaryDisplayColor, COLOR_STYLES } from "@/lib/colorMap";

const props = defineProps<{ card: CardData | null }>();
const emit = defineEmits<{ (e: "close"): void }>();

const TYPE_LABELS: Record<string, string> = {
  Leader: "领航", Character: "角色", Stage: "舞台", Event: "事件",
};
const RARITY_BG: Record<string, string> = {
  L: "bg-yellow-500 text-black", SR: "bg-pink-500 text-white", R: "bg-sky-500 text-white",
  UC: "bg-gray-500 text-white", U: "bg-gray-500 text-white", C: "bg-gray-700 text-gray-300",
  SEC: "bg-red-600 text-white", P: "bg-emerald-500 text-white",
};
const RARITY_LABEL: Record<string, string> = {
  L: "领袖", SR: "超稀有", R: "稀有", UC: "罕见", U: "罕见", C: "普通", SEC: "隐藏稀有", P: "宣传",
};

const displayColor = computed(() => (props.card ? toDisplayColor(props.card.color) : ""));
const colorStyle = computed(() => (props.card ? COLOR_STYLES[primaryDisplayColor(props.card.color)] : undefined));

function onImgError(e: Event) {
  (e.target as HTMLImageElement).src = "/sprites/CardBack.png";
}
</script>

<template>
  <Modal v-if="card" :open="!!card" :title="card.name" @close="emit('close')">
    <div class="flex gap-4">
      <div class="relative h-44 w-32 shrink-0 overflow-hidden rounded-lg bg-gray-800">
        <img
          :src="card.sprite ?? '/sprites/CardBack.png'"
          :alt="card.name"
          class="h-full w-full object-cover"
          loading="lazy"
          @error="onImgError"
        />
        <div v-if="colorStyle" :class="['absolute bottom-0 left-0 right-0 h-1', colorStyle.bg]" />
      </div>

      <div class="flex min-w-0 flex-col gap-2 text-sm">
        <div class="flex flex-wrap items-center gap-1.5">
          <span class="text-xs font-bold text-orange-400">{{ card.number }}</span>
          <span :class="['rounded px-1.5 py-0.5 text-xs font-bold text-white', colorStyle?.bg ?? 'bg-gray-700']">
            {{ displayColor }}
          </span>
          <span class="text-xs text-gray-400">{{ TYPE_LABELS[card.type] ?? card.type }}</span>
        </div>

        <div class="flex flex-wrap items-center gap-1.5">
          <span
            v-if="card.rarity"
            :class="['rounded px-1.5 py-0.5 text-xs font-bold', RARITY_BG[card.rarity] ?? 'bg-gray-700 text-white']"
          >
            {{ RARITY_LABEL[card.rarity] ?? card.rarity }}
          </span>
          <span v-if="card.subscript > 0" class="text-xs font-bold text-yellow-400">角标 {{ card.subscript }}</span>
        </div>

        <p v-if="card.property" class="text-xs text-gray-400">
          属性 <span class="text-white">{{ card.property }}</span>
        </p>
        <p v-if="card.power > 0" class="text-xs">
          <span class="mr-1 text-gray-400">威力</span><span class="font-bold text-white">{{ card.power.toLocaleString() }}</span>
        </p>
        <p v-if="card.cost > 0" class="text-xs">
          <span class="mr-1 text-gray-400">费用</span><span class="font-bold text-white">{{ card.cost }}</span>
        </p>
        <p v-if="card.counter > 0" class="text-xs">
          <span class="mr-1 text-gray-400">反击</span><span class="font-bold text-white">+{{ card.counter }}</span>
        </p>

        <div v-if="card.keyWords.length > 0" class="flex flex-wrap gap-1">
          <span v-for="k in card.keyWords" :key="k" class="rounded bg-blue-900/60 px-1.5 py-0.5 text-xs text-blue-300">
            {{ k }}
          </span>
        </div>

        <p v-if="card.effectText" class="max-w-52 text-xs leading-relaxed text-gray-300">
          {{ card.effectText }}
        </p>
      </div>
    </div>
  </Modal>
</template>
