// opcgpro-web/src/components/game/MulliganOverlay.tsx
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useGameStore } from "@/store/gameStore";
import { GameRequest } from "@/net/GameRequest";
import { getCard } from "@/data/CardLoader";
import CardItem from "@/components/ui/CardItem";
import { useResponsive } from "@/hooks/useResponsive";

export default function MulliganOverlay() {
  const my = useGameStore((s) => s.my);
  const opp = useGameStore((s) => s.opponent);
  const firstPlayerChosen = useGameStore((s) => s.firstPlayerChosen);
  const isFirst = useGameStore((s) => s.isFirstPlayer);
  const mulliganBothDone = useGameStore((s) => s.mulliganBothDone);
  const { cardSize } = useResponsive();

  if (!my) return null;
  if (!firstPlayerChosen) return null;
  if (mulliganBothDone) return null;

  const myDone = my.mulliganDone;
  const oppDone = opp?.mulliganDone ?? false;
  const choosing = !myDone;

  const handCards = my.handCardNumbers.map((n) => getCard(n) ?? null);

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 bg-black/80 flex flex-col items-center justify-center gap-6"
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      >
        <div className="text-center">
          <p className="text-white text-lg font-bold mb-1">{isFirst ? "你是先手" : "你是后手"}</p>
          <p className="text-gray-400 text-sm">
            {choosing ? "是否要更换起始手牌？" : oppDone ? "进入对局..." : "等待对手选择..."}
          </p>
        </div>

        <div className="flex items-center justify-center gap-2 px-4">
          {handCards.map((card, i) => (
            <motion.div
              key={`mulligan-${card?.number ?? i}-${i}`}
              initial={{ y: 60, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ delay: i * 0.08, type: "spring", stiffness: 200 }}
            >
              <CardItem card={card} size={cardSize === "sm" ? "md" : "lg"} />
            </motion.div>
          ))}
        </div>

        {choosing && (
          <motion.div className="flex gap-4"
            initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.4 }}>
            <button onClick={() => GameRequest.mulligan(true)}
              className="bg-blue-600 hover:bg-blue-500 text-white px-8 py-3 rounded-lg font-bold text-base transition-colors">
              更换
            </button>
            <button onClick={() => GameRequest.mulligan(false)}
              className="bg-orange-500 hover:bg-orange-400 text-white px-8 py-3 rounded-lg font-bold text-base transition-colors">
              保留
            </button>
          </motion.div>
        )}

        {!choosing && (
          <motion.div className="flex items-center gap-3"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
            <div className="w-5 h-5 border-2 border-white/40 border-t-white rounded-full animate-spin" />
            <span className="text-gray-300 text-sm">等待对手完成选择...</span>
          </motion.div>
        )}
      </motion.div>
    </AnimatePresence>
  );
}

// opcgpro-vue/src/components/game/MulliganOverlay.vue
<script setup lang="ts">
import { computed } from "vue";
import { useStore } from "@/composables/useStore";
import { useGameStore } from "@/store/gameStore";
import { GameRequest } from "@/net/GameRequest";
import { getCard } from "@/data/CardLoader";
import CardItem from "@/components/ui/CardItem.vue";
import { useResponsive } from "@/composables/useResponsive";

const my = useStore(useGameStore, (s) => s.my);
const opp = useStore(useGameStore, (s) => s.opponent);
const isFirst = useStore(useGameStore, (s) => s.currentTurn || s.firstPlayer === 0);
const mulliganBothDone = useStore(useGameStore, (s) => s.mulliganBothDone);
const { cardSize } = useResponsive();

const visible = computed(() => !!my.value && !mulliganBothDone.value);
const myDone = computed(() => my.value?.mulliganDone ?? false);
const oppDone = computed(() => opp.value?.mulliganDone ?? false);
const choosing = computed(() => !myDone.value);
const handCards = computed(() => (my.value ? my.value.handCardNumbers.map((n) => getCard(n) ?? null) : []));
const mulliganCardSize = computed(() => (cardSize.value === "sm" ? "md" : "lg"));
</script>

<template>
  <Transition name="fade">
    <div v-if="visible" class="fixed inset-0 z-50 flex flex-col items-center justify-center gap-6 bg-black/80">
      <div class="text-center">
        <p class="mb-1 text-lg font-bold text-white">{{ isFirst ? "你是先手" : "你是后手" }}</p>
        <p class="text-sm text-gray-400">
          {{ choosing ? "是否要更换起始手牌？" : oppDone ? "进入对局..." : "等待对手选择..." }}
        </p>
      </div>

      <div class="flex items-center justify-center gap-2 px-4">
        <CardItem v-for="(card, i) in handCards" :key="`mulligan-${card?.number ?? i}-${i}`" :card="card" :size="mulliganCardSize" />
      </div>

      <div v-if="choosing" class="flex gap-4">
        <button class="rounded-lg bg-blue-600 px-8 py-3 text-base font-bold text-white transition-colors hover:bg-blue-500" @click="GameRequest.mulligan(true)">
          更换
        </button>
        <button class="rounded-lg bg-orange-500 px-8 py-3 text-base font-bold text-white transition-colors hover:bg-orange-400" @click="GameRequest.mulligan(false)">
          保留
        </button>
      </div>

      <div v-else class="flex items-center gap-3">
        <div class="h-5 w-5 animate-spin rounded-full border-2 border-white/40 border-t-white" />
        <span class="text-sm text-gray-300">等待对手完成选择...</span>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active { transition: opacity 0.2s ease; }
.fade-enter-from,
.fade-leave-to { opacity: 0; }
</style>
