// opcgpro-vue/src/components/game/GameBoard.vue
<script setup lang="ts">
import { computed, ref, provide } from "vue";
import { useStore } from "@/composables/useStore";
import { useGameStore } from "@/store/gameStore";
import { useStageScale } from "@/composables/useStageScale";
import { CARD_SIZE_OVERRIDE } from "@/composables/useResponsive";
import { getCard } from "@/data/CardLoader";
import PlayerMat from "./PlayerMat.vue";
import PhaseTrack from "./PhaseTrack.vue";
import GameLog from "./GameLog.vue";
import GameActions from "./GameActions.vue";
import AnimationLayer from "./AnimationLayer.vue";
import RevealOverlay from "./RevealOverlay.vue";
import GameChatPanel from "./GameChatPanel.vue";

/**
 * GameBoard — 牌桌渲染（对战页与回放页共用）。
 *
 * 纯展示层：从 gameStore 读取镜像状态并按固定 1280×720 画布 scale-to-fit 渲染。
 * 不含玩家专属浮层（轮抽/Prompt/菜单/等待遮罩/结算弹窗等）——那些由 GamePage 叠加。
 * 回放页传 isPlayback 即可复用同一套牌桌。
 *
 * 与 opcgpro-web/src/components/game/GameBoard.tsx 一一对齐：
 * - 1280×720 固定画布 + useStageScale 等比缩放
 * - 三栏（LeftRail + Main + RightRail）布局
 * - 左栏「选中卡」面板的 focusCard 推导逻辑是 Vue 端自创（web 是空占位），
 *   用 @hover-card 事件链接 PlayerMat/HandArea/FieldArea/LeaderCard 的 emit
 */
const STAGE_W = 1280;
const STAGE_H = 720;

const props = defineProps<{
  isObserver: boolean;
  isPlayback: boolean;
}>();

const currentTurn = useStore(useGameStore, (s) => s.currentTurn);
const phase = useStore(useGameStore, (s) => s.phase);
const myName = useStore(useGameStore, (s) => s.myName);
const opponentName = useStore(useGameStore, (s) => s.opponentName);
const my = useStore(useGameStore, (s) => s.my);
const opponent = useStore(useGameStore, (s) => s.opponent);
const selectedHandIndex = useStore(useGameStore, (s) => s.selectedHandIndex);
const selectedFieldId = useStore(useGameStore, (s) => s.selectedFieldId);

// 设计画布等比缩放
const stageScale = useStageScale(STAGE_W, STAGE_H);
// 强制画布内所有 CardItem 用 sm 尺寸（与 web 端 CardSizeOverride.Provider 一致）
provide(CARD_SIZE_OVERRIDE, ref<"sm" | "md" | "lg">("sm"));

const showPlayerControls = computed(() => !props.isObserver && !props.isPlayback);

// ── 左栏「选中卡」面板 ──────────────────────────────────────────────────
// Vue 端自创：依据 hover-card 事件链 + selectedHandIndex + selectedFieldId
// 推导当前需展示详情的卡。web 对应位置是空 5:7 占位，无推导逻辑。
const hoveredCard = ref<ReturnType<typeof getCard> | null>(null);
const focusCard = computed(() => {
  if (hoveredCard.value) return hoveredCard.value;
  if (selectedHandIndex.value !== null && my.value) {
    const n = my.value.handCardNumbers[selectedHandIndex.value];
    if (n) return getCard(n) ?? null;
  }
  if (selectedFieldId.value !== null) {
    if (my.value) {
      if (selectedFieldId.value === my.value.leaderId && my.value.leaderNumber)
        return getCard(my.value.leaderNumber) ?? null;
      const myFc = my.value.fieldCards.find((c) => c.id === selectedFieldId.value);
      if (myFc?.number) return getCard(myFc.number) ?? null;
    }
    if (opponent.value) {
      if (selectedFieldId.value === opponent.value.leaderId && opponent.value.leaderNumber)
        return getCard(opponent.value.leaderNumber) ?? null;
      const oppFc = opponent.value.fieldCards.find((c) => c.id === selectedFieldId.value);
      if (oppFc?.number) return getCard(oppFc.number) ?? null;
    }
  }
  return null;
});
</script>

<template>
  <!-- 背景层（画布外，全屏铺底） -->
  <div class="absolute inset-0 bg-[radial-gradient(circle_at_center,_rgba(33,92,145,0.26),_transparent_62%),linear-gradient(135deg,_#0b1a2c,_#07111f_48%,_#0a1524)]" />
  <div class="absolute inset-0 opacity-[0.08] [background-image:linear-gradient(rgba(255,255,255,.6)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.6)_1px,transparent_1px)] [background-size:18px_18px]" />

  <!-- 动画 / 揭示（不随画布缩放） -->
  <AnimationLayer />
  <RevealOverlay />

  <!-- 固定设计画布 + 整体等比缩放居中（scale-to-fit） -->
  <div class="absolute inset-0 z-10 flex items-center justify-center">
    <div
      class="relative shrink-0"
      :style="{
        width: `${STAGE_W}px`,
        height: `${STAGE_H}px`,
        transform: `scale(${stageScale})`,
        transformOrigin: 'center',
      }"
    >
      <div class="absolute inset-3 flex gap-3">
        <!-- 左栏：选中卡 + 记录 -->
        <aside class="flex h-full min-h-0 w-52 shrink-0 flex-col gap-3">
          <section class="min-h-0 flex-1 rounded-md border border-sky-200/15 bg-slate-950/55 p-3 shadow-inner shadow-black/30">
            <h2 class="text-xs font-black text-slate-300">选中卡</h2>
            <div v-if="focusCard" class="mt-2 flex flex-col gap-2">
              <div class="truncate text-sm font-bold text-sky-100">{{ focusCard.name }}</div>
              <div v-if="focusCard.power" class="text-xs text-sky-300">力量 {{ focusCard.power.toLocaleString() }}</div>
              <div v-if="focusCard.counter" class="text-xs text-amber-300">反击 +{{ focusCard.counter }}</div>
              <div v-if="focusCard.cost != null" class="text-xs text-slate-400">费用 {{ focusCard.cost }}</div>
              <div v-if="focusCard.type" class="text-xs text-slate-500">{{ focusCard.type }}</div>
            </div>
            <div v-else class="mt-3 aspect-[5/7] rounded-md border border-dashed border-slate-600/70 bg-black/20" />
          </section>
          <section class="h-36 rounded-md border border-sky-200/15 bg-slate-950/55 p-3 shadow-inner shadow-black/30 xl:h-44">
            <h2 class="text-xs font-black text-slate-300">记录</h2>
          </section>
        </aside>

        <!-- 中栏：牌桌（对手区 + 阶段条 + 己方区） -->
        <main class="relative z-0 flex min-w-0 flex-1 flex-col gap-2">
          <PlayerMat side="opponent" :is-observer="isObserver" :is-playback="isPlayback" @hover-card="(c: any) => hoveredCard = c" />
          <PhaseTrack :current-turn="currentTurn" :phase="phase" />
          <PlayerMat side="my" :is-observer="isObserver" :is-playback="isPlayback" @hover-card="(c: any) => hoveredCard = c" />
        </main>

        <!-- 右栏：玩家信息 + 日志 + 操作 -->
        <aside class="relative z-40 flex h-full min-h-0 w-44 shrink-0 flex-col gap-3">
          <section class="rounded-md border border-sky-200/15 bg-slate-950/65 p-3 shadow-inner shadow-black/30">
            <p class="text-xs font-black text-slate-300">对手</p>
            <p class="mt-1 truncate text-sm font-black text-white">{{ opponentName || '对手' }}</p>
            <div class="my-3 h-px bg-white/10" />
            <p class="text-xs font-black text-slate-300">我</p>
            <p class="mt-1 truncate text-sm font-black text-sky-100">{{ myName || '我' }}</p>
          </section>
          <!-- 玩家/回放模式显示日志；玩家模式额外显示操作；观战模式完全隐藏 -->
          <template v-if="showPlayerControls || isPlayback">
            <section class="relative min-h-0 flex-1 overflow-y-auto rounded-md border border-sky-200/15 bg-slate-950/65 p-3 shadow-inner shadow-black/30">
              <h2 class="text-xs font-black text-slate-300">操作日志</h2>
              <GameLog />
            </section>
            <section v-if="showPlayerControls" class="rounded-md border border-sky-200/15 bg-slate-950/65 p-3 shadow-inner shadow-black/30">
              <h2 class="mb-2 text-xs font-black text-slate-300">操作</h2>
              <GameActions />
            </section>
          </template>
        </aside>
      </div>
    </div>
  </div>

  <!-- 局内聊天（固定屏幕角，不随画布缩放；回放模式内部自隐） -->
  <GameChatPanel :is-playback="isPlayback" />
</template>

// opcgpro-web/src/components/game/GameBoard.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import HandArea from "@/components/game/HandArea";
import FieldArea from "@/components/game/FieldArea";
import LeaderCard from "@/components/game/LeaderCard";
import LifeArea from "@/components/game/LifeArea";
import DonArea from "@/components/game/DonArea";
import DonDeckPile from "@/components/game/DonDeckPile";
import DeckPile from "@/components/game/DeckPile";
import TrashPile from "@/components/game/TrashPile";
import StageSlot from "@/components/game/StageSlot";
import GameLog from "@/components/game/GameLog";
import GameActions from "@/components/game/GameActions";
import AnimationLayer from "@/components/game/AnimationLayer";
import BattleRelationLayer from "@/components/game/BattleRelationLayer";
import RevealOverlay from "@/components/game/RevealOverlay";
import GameChatPanel from "@/components/game/GameChatPanel";
import { useGameStore } from "@/store/gameStore";
import { useStageScale } from "@/hooks/useStageScale";
import { CardSizeOverride } from "@/hooks/useResponsive";
import { PHASE_LABELS } from "@/game/battle/BattlePhase";

// 对战页固定设计画布尺寸：内容按此基准布局，整体等比缩放铺满视口
const STAGE_W = 1280;
const STAGE_H = 720;

function PlayerMat({
  side,
  isObserver,
  isPlayback,
}: {
  side: "my" | "opponent";
  isObserver: boolean;
  isPlayback: boolean;
}) {
  const isOpponent = side === "opponent";
  const canShowDon = !isObserver && !isPlayback;
  const leaderStage = (
    <div className="flex items-end justify-center gap-4 md:gap-5">
      <LeaderCard side={side} />
      <StageSlot side={side} />
    </div>
  );
  const donZone = canShowDon ? (
    <div className="flex w-full max-w-[32rem] items-center gap-2">
      <DonDeckPile side={side} />
      <div className="min-w-0 flex-1">
        <DonArea side={side} />
      </div>
    </div>
  ) : null;
  const fieldZone = (
    <div className="min-w-0 flex-1 self-stretch">
      <FieldArea side={side} />
    </div>
  );

  return (
    <section
      className={[
        "relative min-h-0 min-w-0 flex-1 rounded-md border border-sky-200/15 shadow-inner shadow-black/35",
        isOpponent ? "bg-red-950/[0.07]" : "bg-sky-950/[0.16]",
      ].join(" ")}
    >
      <div className={`absolute inset-x-0 ${isOpponent ? "bottom-0 h-px bg-red-300/20" : "top-0 h-px bg-sky-300/20"}`} />

      <div className={`absolute right-3 z-20 flex flex-col gap-2 ${isOpponent ? "top-1/2 -translate-y-1/2" : "top-[45%] -translate-y-1/2"}`}>
        <DeckPile side={side} />
        <TrashPile side={side} />
      </div>

      <div className="grid h-full min-w-0 grid-rows-[1fr_auto_1fr] gap-2 p-3 pr-32 md:pr-36">
        {isOpponent ? (
          <div className="relative min-h-0 min-w-0 pl-24 md:pl-28">
            <HandArea side={side} hidden />
          </div>
        ) : (
          <div className="relative flex min-h-0 min-w-0 items-stretch gap-4 pl-24 md:pl-28">
            <div className="absolute left-0 top-0 z-20">
              <LifeArea side={side} />
            </div>
            {fieldZone}
          </div>
        )}

        <div className="grid min-h-0 min-w-0 grid-cols-[minmax(14rem,0.9fr)_minmax(16rem,1.1fr)] items-center gap-4">
          <div className="min-w-0">{donZone}</div>
          <div className="justify-self-center">{leaderStage}</div>
        </div>

        {isOpponent ? (
          <div className="relative flex min-h-0 min-w-0 items-stretch gap-4 pl-24 md:pl-28">
            <div className="absolute left-0 top-0 z-20">
              <LifeArea side={side} />
            </div>
            {fieldZone}
          </div>
        ) : (
          <div className="relative -ml-[233px] min-h-0 min-w-0">
            <HandArea side={side} hidden={isObserver} />
          </div>
        )}
      </div>
    </section>
  );
}

// 回合五阶段（平时显示）
const TURN_FLOW = ["Reset", "Draw", "Don", "Main", "End"];
// 战斗子流程（攻击宣言后显示后端真实的 4 个步骤）
const BATTLE_FLOW = ["Attack", "Block", "Counter", "Damage"];
const BATTLE_PHASES = new Set(BATTLE_FLOW);
// #238 每回合倒计时基准秒数（纯前端提示，不判负；后端无权威计时）
const TURN_SECONDS = 300;

// #238 回合倒计时徽章：每次 turnCount 变化即从 TURN_SECONDS 重新倒数；仅对局中（live）走秒
function TurnTimer({ turnCount, live }: { turnCount: number; live: boolean }) {
  const [remain, setRemain] = useState(TURN_SECONDS);

  // 回合切换即重置（turnCount 由后端权威快照驱动，天然与实际回合对齐）
  useEffect(() => {
    setRemain(TURN_SECONDS);
  }, [turnCount]);

  useEffect(() => {
    if (!live) return;
    const id = setInterval(() => {
      setRemain((r) => (r > 0 ? r - 1 : 0));
    }, 1000);
    return () => clearInterval(id);
  }, [live, turnCount]);

  const mm = Math.floor(remain / 60);
  const ss = remain % 60;
  const low = remain <= 30;
  return (
    <span
      className={[
        "shrink-0 rounded-md px-2 py-1 font-mono text-[11px] font-black tabular-nums",
        low
          ? "bg-red-500/25 text-red-200 ring-1 ring-red-400/50"
          : "bg-slate-700/50 text-slate-200 ring-1 ring-white/10",
      ].join(" ")}
      title="本回合计时（前端提示，不判负）"
    >
      ⏱ {mm}:{ss.toString().padStart(2, "0")}
    </span>
  );
}

function PhaseTrack({
  currentTurn,
  phase,
  turnCount,
  live,
}: {
  currentTurn: boolean;
  phase: string;
  turnCount: number;
  live: boolean;
}) {
  const inBattle = BATTLE_PHASES.has(phase);
  const flow = inBattle ? BATTLE_FLOW : TURN_FLOW;
  return (
    <div className="flex shrink-0 items-center justify-center gap-2 py-0.5">
      <TurnTimer turnCount={turnCount} live={live} />
      <span
        className={[
          "shrink-0 rounded-md px-2.5 py-1 text-[11px] font-black",
          currentTurn
            ? "bg-sky-500/20 text-sky-200 ring-1 ring-sky-400/40"
            : "bg-red-500/20 text-red-200 ring-1 ring-red-400/40",
        ].join(" ")}
      >
        {currentTurn ? "我的回合" : "对手回合"}
        {inBattle ? " · 战斗中" : ""}
      </span>
      <div className="flex items-center gap-1.5">
        {flow.map((p) => {
          const isActive = p === phase;
          return (
            <div
              key={p}
              className={[
                "rounded-md px-2.5 py-1 text-[11px] font-black transition-colors",
                isActive
                  ? currentTurn
                    ? "bg-sky-500 text-white shadow shadow-sky-500/40"
                    : "bg-red-500 text-white shadow shadow-red-500/40"
                  : "border border-white/10 bg-slate-800/60 text-slate-400",
              ].join(" ")}
            >
              {PHASE_LABELS[p] ?? p}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function LeftRail() {
  return (
    <aside className="flex h-full min-h-0 w-52 shrink-0 flex-col gap-3 pb-28">
      <section className="min-h-0 flex-1 rounded-md border border-sky-200/15 bg-slate-950/55 p-3 shadow-inner shadow-black/30">
        <h2 className="text-xs font-black text-slate-300">选中卡</h2>
        <div className="mt-3 aspect-[5/7] rounded-md border border-dashed border-slate-600/70 bg-black/20" />
      </section>
      <section className="h-36 rounded-md border border-sky-200/15 bg-slate-950/55 p-3 shadow-inner shadow-black/30 xl:h-44">
        <h2 className="text-xs font-black text-slate-300">记录</h2>
      </section>
    </aside>
  );
}

function RightRail({
  myName,
  opponentName,
  isObserver,
  isPlayback,
}: {
  myName: string;
  opponentName: string;
  isObserver: boolean;
  isPlayback: boolean;
}) {
  return (
    <aside className="relative z-40 flex h-full min-h-0 w-44 shrink-0 flex-col gap-3">
      <section className="rounded-md border border-sky-200/15 bg-slate-950/65 p-3 shadow-inner shadow-black/30">
        <p className="text-xs font-black text-slate-300">对手</p>
        <p className="mt-1 truncate text-sm font-black text-white">{opponentName || "对手"}</p>
        <div className="my-3 h-px bg-white/10" />
        <p className="text-xs font-black text-slate-300">我</p>
        <p className="mt-1 truncate text-sm font-black text-sky-100">{myName || "我"}</p>
      </section>
      {!isObserver && !isPlayback && (
        <>
          <section className="relative min-h-0 flex-1 overflow-y-auto rounded-md border border-sky-200/15 bg-slate-950/65 p-3 shadow-inner shadow-black/30">
            <h2 className="text-xs font-black text-slate-300">操作日志</h2>
            <GameLog />
          </section>
          <section className="rounded-md border border-sky-200/15 bg-slate-950/65 p-3 shadow-inner shadow-black/30">
            <h2 className="mb-2 text-xs font-black text-slate-300">操作</h2>
            <GameActions />
          </section>
        </>
      )}
      {isPlayback && (
        <section className="relative min-h-0 flex-1 overflow-y-auto rounded-md border border-sky-200/15 bg-slate-950/65 p-3 shadow-inner shadow-black/30">
          <h2 className="text-xs font-black text-slate-300">操作日志</h2>
          <GameLog />
        </section>
      )}
    </aside>
  );
}

/**
 * GameBoard — 牌桌渲染（对战页与回放页共用）
 *
 * 纯展示层：从 gameStore 读取镜像状态并按固定 1280×720 画布 scale-to-fit 渲染。
 * 不含玩家专属浮层（轮抽/Prompt/菜单等）与结算弹窗——那些由各页面自行叠加。
 * 回放页传 isPlayback 即可复用同一套牌桌。
 */
export default function GameBoard({
  isObserver,
  isPlayback,
}: {
  isObserver: boolean;
  isPlayback: boolean;
}) {
  const currentTurn = useGameStore((s) => s.currentTurn);
  const phase = useGameStore((s) => s.phase);
  const turnCount = useGameStore((s) => s.turnCount);
  const myName = useGameStore((s) => s.myName);
  const opponentName = useGameStore((s) => s.opponentName);

  const stageScale = useStageScale(STAGE_W, STAGE_H);
  const stageRef = useRef<HTMLDivElement>(null);

  return (
    <>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_rgba(33,92,145,0.26),_transparent_62%),linear-gradient(135deg,_#0b1a2c,_#07111f_48%,_#0a1524)]" />
      <div className="absolute inset-0 opacity-[0.08] [background-image:linear-gradient(rgba(255,255,255,.6)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.6)_1px,transparent_1px)] [background-size:18px_18px]" />

      <AnimationLayer />
      <RevealOverlay />

      {/* 固定设计画布 + 整体等比缩放居中（scale-to-fit），保证任何宽高比下比例恒定、不裁切 */}
      <div className="absolute inset-0 z-10 flex items-center justify-center">
        <CardSizeOverride.Provider value="sm">
          <div
            ref={stageRef}
            className="relative shrink-0"
            style={{
              width: STAGE_W,
              height: STAGE_H,
              transform: `scale(${stageScale})`,
              transformOrigin: "center",
            }}
          >
            <BattleRelationLayer />
            <div className="absolute inset-3 flex gap-3">
              <LeftRail />

              <main className="relative z-0 flex min-w-0 flex-1 flex-col gap-2">
                <PlayerMat side="opponent" isObserver={isObserver} isPlayback={isPlayback} />

                <PhaseTrack
                  currentTurn={currentTurn}
                  phase={phase}
                  turnCount={turnCount}
                  live={!isObserver && !isPlayback}
                />

                <PlayerMat side="my" isObserver={isObserver} isPlayback={isPlayback} />
              </main>

              <RightRail
                myName={myName}
                opponentName={opponentName}
                isObserver={isObserver}
                isPlayback={isPlayback}
              />
            </div>

          </div>
        </CardSizeOverride.Provider>
      </div>

      {/* 局内聊天（固定屏幕角，不随画布缩放；回放模式内部自隐） */}
      <GameChatPanel isPlayback={isPlayback} />
    </>
  );
}
