// opcgpro-vue/src/components/game/HandArea.vue
<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from "vue";
import { useStore } from "@/composables/useStore";
import { useGameStore } from "@/store/gameStore";
import { useResponsive } from "@/composables/useResponsive";
import { useIsDefender } from "@/composables/useIsDefender";
import { GameRequest } from "@/net/GameRequest";
import CardItem from "@/components/ui/CardItem.vue";
import { getCard } from "@/data/CardLoader";

const props = withDefaults(defineProps<{ side: "my" | "opponent"; hidden?: boolean }>(), { hidden: false });
const emit = defineEmits<{ (e: "hover-card", card: ReturnType<typeof getCard> | null): void }>();

const player = useStore(useGameStore, (s) => (props.side === "my" ? s.my : s.opponent));
const currentTurn = useStore(useGameStore, (s) => s.currentTurn);
const phase = useStore(useGameStore, (s) => s.phase);
const isPending = useStore(useGameStore, (s) => s.isPending);
const selectedHandIndex = useStore(useGameStore, (s) => s.selectedHandIndex);
const { cardSize } = useResponsive();
const isDefender = useIsDefender();

const wrapRef = ref<HTMLDivElement | null>(null);
const wrapW = ref(0);
let ro: ResizeObserver | null = null;
let raf = 0;
// rAF 包裹 + 阈值防抖：避免 ResizeObserver 自反馈循环与亚像素抖动导致手牌反复重排（#143/#161）
const updateWrapW = () => {
  const w = wrapRef.value?.clientWidth ?? 0;
  if (Math.abs(wrapW.value - w) > 1) wrapW.value = w;
};
onMounted(() => {
  if (wrapRef.value) {
    wrapW.value = wrapRef.value.clientWidth;
    ro = new ResizeObserver(() => { cancelAnimationFrame(raf); raf = requestAnimationFrame(updateWrapW); });
    ro.observe(wrapRef.value);
  }
});
onUnmounted(() => { cancelAnimationFrame(raf); ro?.disconnect(); });

const cards = computed(() => {
  if (!player.value) return [];
  return props.side === "my" ? player.value.handCardNumbers.map((n) => getCard(n) ?? null) : Array.from({ length: player.value.handCount }, () => null);
});

const stableKeys = computed(() => {
  const seen: Record<string, number> = {};
  return cards.value.map((card, i) => {
    const base = props.side === "my" ? (player.value?.handCardNumbers[i] ?? "null") : "back";
    const occ = (seen[base] = (seen[base] ?? 0) + 1);
    return `${base}#${occ}`;
  });
});

const isCounterStep = computed(() => !props.hidden && props.side === "my" && phase.value === "Counter" && isDefender.value);
const myActiveDon = computed(() => props.side === "my" && player.value ? player.value.costActive : 0);

function isCounterEventPlayable(card: ReturnType<typeof getCard> | null, i: number): boolean {
  if (!isCounterStep.value || !card) return false;
  if ((card.counter ?? 0) > 0) return false;
  if (!card.effectTags?.includes("EventCounter")) return false;
  const effectiveCost = player.value?.handCardCosts?.[i] ?? card.cost;
  return effectiveCost <= myActiveDon.value;
}

const marginLeft = computed(() => {
  const n = cards.value.length;
  const cardW = cardSize.value === "sm" ? 72 : cardSize.value === "md" ? 96 : 128;
  const GAP = 8;
  const PAD = 24;
  const minStep = Math.round(cardW * 0.22); // 重叠下限：每张至少露出 ~22%（手牌很多时也能铺下不溢出）
  const avail = Math.max(0, wrapW.value - PAD);
  let step = cardW + GAP;
  if (n > 1 && avail > 0) { const fitStep = (avail - cardW) / (n - 1); step = Math.max(minStep, Math.min(cardW + GAP, fitStep)); }
  // 取整：避免亚像素 marginLeft 在过渡动画下反复微动（漂移）
  return Math.round(step - cardW);
});

// 扇形手牌：每张按到中心的偏移旋转（源自 battle.jsx 手牌 rotate (i-mid)*2.6deg）
function fanStyle(i: number, n: number) {
  const mid = (n - 1) / 2;
  const isMy = props.side === "my";
  const deg = (i - mid) * (isMy ? 2.6 : 2);
  const ty = isMy ? Math.abs(i - mid) * 5 : 0;
  return {
    transform: `rotate(${deg}deg) translateY(${ty}px)`,
    transformOrigin: isMy ? "bottom center" : "top center",
  };
}

function handleClick(i: number) {
  if (props.hidden || isPending.value) return;
  if (isCounterStep.value) { const c = cards.value[i]; if (c && (c.counter ?? 0) > 0) GameRequest.playCounterFromHand(i); else if (isCounterEventPlayable(c, i)) GameRequest.playCounterEvent(i); return; }
  if (props.side !== "my" || !currentTurn.value) return;
  useGameStore.getState().setSelectedHand(selectedHandIndex.value === i ? null : i);
}
</script>

<template>
  <div v-if="!player" class="min-h-20" />
  <div v-else ref="wrapRef" class="-my-5 flex min-h-24 w-full min-w-0 items-end justify-center overflow-x-auto px-3 py-6 lg:min-h-32">
    <TransitionGroup :name="side === 'my' ? 'hand-my' : 'hand-opp'">
      <div v-for="(card, i) in cards" :key="stableKeys[i]"
        :class="['relative hover:z-20', (isCounterStep && ((card?.counter ?? 0) > 0 || isCounterEventPlayable(card, i))) ? 'rounded-md ring-2 ring-amber-400 animate-pulse' : '']"
        :style="{ marginLeft: i === 0 ? '0' : `${marginLeft}px` }"
        @mouseenter="emit('hover-card', card)" @mouseleave="emit('hover-card', null)">
        <div :style="fanStyle(i, cards.length)">
          <CardItem :card="card" :is-selected="!hidden && selectedHandIndex === i" :face-down="hidden || card === null" :size="cardSize" hide-power :cost-buff="side === 'my' && card && player?.handCardCosts?.[i] != null ? player.handCardCosts[i] - card.cost : 0" @click="handleClick(i)" />
        </div>
      </div>
    </TransitionGroup>
    <span v-if="cards.length === 0" class="text-xs text-gray-700">{{ hidden ? "对手手牌" : "手牌为空" }}</span>
  </div>
</template>

<style scoped>
.hand-my-enter-active,
.hand-opp-enter-active,
.hand-my-leave-active,
.hand-opp-leave-active,
.hand-my-move-active,
.hand-opp-move-active { transition: all 0.25s ease; }
.hand-my-enter-from { transform: translateY(36px); opacity: 0; }
.hand-my-leave-to   { transform: translateY(-24px); opacity: 0; }
.hand-opp-enter-from { transform: translateY(-24px); opacity: 0; }
.hand-opp-leave-to  { transform: translateY(24px); opacity: 0; }
</style>

// opcgpro-web/src/components/game/HandArea.tsx
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { useGameStore } from "@/store/gameStore";
import { useResponsive } from "@/hooks/useResponsive";
import { useIsDefender } from "@/hooks/useIsDefender";
import { GameRequest } from "@/net/GameRequest";
import CardItem from "@/components/ui/CardItem";
import { getCard } from "@/data/CardLoader";

interface Props {
  side: "my" | "opponent";
  hidden?: boolean;
}

export default function HandArea({ side, hidden = false }: Props) {
  const player = useGameStore((s) => (side === "my" ? s.my : s.opponent));
  const currentTurn = useGameStore((s) => s.currentTurn);
  const phase = useGameStore((s) => s.phase);
  const isPending = useGameStore((s) => s.isPending);
  const selectedHandIndex = useGameStore((s) => s.selectedHandIndex);
  const setSelectedHand = useGameStore((s) => s.setSelectedHand);
  const { cardSize } = useResponsive();
  const isDefender = useIsDefender();

  // 测量手牌容器实际可用宽度（画布内为未缩放设计像素），用于动态计算重叠量
  const wrapRef = useRef<HTMLDivElement>(null);
  const [wrapW, setWrapW] = useState(0);
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    // rAF 包裹 + 阈值防抖：避免 ResizeObserver 自反馈循环与亚像素抖动导致手牌反复重排（#143/#161）
    const update = () => {
      const w = el.clientWidth;
      setWrapW((prev) => (Math.abs(prev - w) > 1 ? w : prev));
    };
    update();
    let raf = 0;
    const ro = new ResizeObserver(() => {
      cancelAnimationFrame(raf);
      raf = requestAnimationFrame(update);
    });
    ro.observe(el);
    return () => { cancelAnimationFrame(raf); ro.disconnect(); };
  }, []);

  if (!player) return <div className="min-h-20" />;

  // 观战时双方手牌都已脱敏，统一按服务端 handCount 生成卡背。
  // 普通玩家视角下，仅己方使用真实手牌列表，对手仍只显示卡背与数量。
  const cards = hidden
    ? Array.from({ length: player.handCount }, () => null)
    : side === "my"
      ? player.handCardNumbers.map((n) => getCard(n) ?? null)
      : Array.from({ length: player.handCount }, () => null);

  // 稳定 key：按卡号 + 同名出现次序，不含数组下标。
  // 这样打出中间某张时，仅被移除那张的 key 消失，其余 key 不变 → 不会整手牌重排乱跳。
  const seen: Record<string, number> = {};
  const stableKeys = cards.map((card, i) => {
    const base = side === "my" ? player.handCardNumbers[i] ?? "null" : "back";
    const occ = (seen[base] = (seen[base] ?? 0) + 1);
    return `${base}#${occ}`;
  });

  // 反击步骤：防守方可点击带反击值的手牌丢弃加反击；
  // 或点击「反击事件」（带 EventCounter 标签且费用可付）从手牌打出。
  // 防守方判断用 isDefender（攻击者属于对手），兼容 GM「对手领袖攻击」在我方回合制造的战斗。
  const isCounterStep = !hidden && side === "my" && phase === "Counter" && isDefender;
  const myActiveDon = side === "my" && player ? player.costActive : 0;
  const effectiveCounter = (c: ReturnType<typeof getCard> | null, i: number) =>
    (side === "my" ? player.handCardCounters?.[i] : undefined) ?? c?.counter ?? 0;

  // 反击事件是否可打：带 EventCounter 标签，且有效费用 ≤ 当前活跃咚
  const isCounterEventPlayable = (c: ReturnType<typeof getCard> | null, i: number) =>
    isCounterStep && !!c && effectiveCounter(c, i) <= 0 &&
    c.effectTags.includes("EventCounter") &&
    ((side === "my" ? player.handCardCosts?.[i] : undefined) ?? c.cost) <= myActiveDon;

  // 动态重叠：让手牌无论多少张都铺满且不溢出。
  // step = 每张相对前一张的水平步进（露出的宽度）；step<cardW 即重叠。
  const cardW = cardSize === "sm" ? 72 : cardSize === "md" ? 96 : 128; // CardItem 各档宽度(px)
  const GAP = 8;                       // 不重叠时的卡间距（≈gap-2）
  const PAD = 24;                      // 容器左右内边距(px-3 各 12)
  const minStep = Math.round(cardW * 0.22); // 重叠下限：每张至少露出 ~22%（手牌很多时也能铺下不溢出）
  const avail = Math.max(0, wrapW - PAD);
  const n = cards.length;
  let step = cardW + GAP;              // 默认：满间距、零重叠
  if (n > 1 && avail > 0) {
    const fitStep = (avail - cardW) / (n - 1);
    step = Math.max(minStep, Math.min(cardW + GAP, fitStep));
  }
  step = Math.round(step);             // 整数步进，杜绝亚像素
  // 整数像素绝对定位（替代 flex 居中 + 负 marginLeft + framer-motion layout）：
  // 每张卡的 x 由整数公式算出，motion.div 用 animate={{x}} 平移到位，不挂 layout、
  // 不依赖浏览器 justify-center → 无亚像素居中、无 layout 反复测量 → 手牌再多也不漂移（#161）。
  const totalW = cardW + (n - 1) * step;
  const startX = Math.round(Math.max(PAD / 2, (wrapW - totalW) / 2)); // 居中起点；溢出则贴左内边距
  const xOf = (i: number) => startX + i * step;                       // 已是整数

  const handleClick = (i: number) => {
    if (hidden || isPending) return;
    if (isCounterStep) {
      const c = cards[i];
      if (c && effectiveCounter(c, i) > 0) GameRequest.playCounterFromHand(i);
      else if (isCounterEventPlayable(c, i)) GameRequest.playCounterEvent(i);
      return;
    }
    if (side !== "my" || !currentTurn) return;
    setSelectedHand(selectedHandIndex === i ? null : i);
  };

  return (
    <div
      ref={wrapRef}
      className="relative z-30 h-full w-full min-w-0 overflow-visible"
    >
      <AnimatePresence>
        {cards.map((card, i) => {
          const counterPlayable =
            (isCounterStep && effectiveCounter(card, i) > 0) || isCounterEventPlayable(card, i);
          return (
            <motion.div
              key={stableKeys[i]}
              initial={{ x: xOf(i), y: side === "my" ? 36 : -24, opacity: 0 }}
              animate={{ x: xOf(i), y: 0, opacity: 1 }}
              exit={{ y: side === "my" ? -24 : 24, opacity: 0 }}
              transition={{
                x: { type: "spring", stiffness: 350, damping: 30 },
                y: { delay: i * 0.04, type: "spring", stiffness: 200 },
                opacity: { delay: i * 0.04 },
              }}
              style={{ position: "absolute", left: 0, bottom: 0 }}
              className={[
                "hover:z-20", // 悬停提升层级，盖过邻牌，便于看清被压住的卡（低于右栏操作区 z-30，避免盖住出牌/结束回合按钮）
                counterPlayable ? "rounded-md ring-2 ring-amber-400 animate-pulse" : "",
              ].join(" ")}
            >
              <CardItem
                card={card}
                isSelected={!hidden && selectedHandIndex === i}
                faceDown={hidden || card === null}
                hidePower
                counterValue={effectiveCounter(card, i)}
                onClick={() => handleClick(i)}
                size={cardSize}
                costBuff={
                  side === "my" && card && player.handCardCosts?.[i] != null
                    ? player.handCardCosts[i] - card.cost
                    : 0
                }
              />
            </motion.div>
          );
        })}
      </AnimatePresence>

      {cards.length === 0 && (
        <span className="absolute inset-0 flex items-center justify-center text-xs text-gray-700">
          {hidden ? "手牌" : "手牌为空"}
        </span>
      )}

      {/* #188 手牌数量角标：我方底部/对手顶部，避开右栏(left 定位)，z-30 + pointer-events-none 不遮点击 */}
      <span
        className={[
          "pointer-events-none absolute left-1 z-30",
          "rounded-full bg-black/60 px-2 py-0.5 text-xs font-bold text-white ring-1 ring-white/20",
          side === "my" ? "bottom-1" : "top-1",
        ].join(" ")}
      >
        {cards.length}
      </span>
    </div>
  );
}
