// opcgpro-vue/src/components/game/OpponentDisconnectBanner.vue
<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from "vue";
import { eventBus } from "@/net/eventBus";

const countdown = ref<number | null>(null);
let timer: ReturnType<typeof setInterval> | null = null;

function onDisconnect(payload: { gracePeriodSeconds: number }) {
  countdown.value = payload.gracePeriodSeconds;
}
function onReconnect() {
  countdown.value = null;
}

onMounted(() => {
  eventBus.on("opponentDisconnected", onDisconnect);
  eventBus.on("opponentReconnected", onReconnect);
});
onUnmounted(() => {
  eventBus.off("opponentDisconnected", onDisconnect);
  eventBus.off("opponentReconnected", onReconnect);
  if (timer) clearInterval(timer);
});

watch(countdown, (n) => {
  if (timer) { clearInterval(timer); timer = null; }
  if (n === null || n <= 0) return;
  timer = setInterval(() => {
    countdown.value = countdown.value !== null && countdown.value > 0 ? countdown.value - 1 : null;
  }, 1000);
});
</script>

<template>
  <div
    v-if="countdown !== null"
    class="absolute left-1/2 top-4 z-40 -translate-x-1/2 animate-pulse rounded-lg bg-yellow-500/90 px-6 py-2 text-sm font-bold text-black shadow-lg"
  >
    对手已断线，等待重连 {{ countdown }}s
  </div>
</template>

// opcgpro-web/src/components/game/OpponentDisconnectBanner.tsx
"use client";

import { useEffect, useState } from "react";
import { eventBus } from "@/net/eventBus";

/**
 * OpponentDisconnectBanner — 对手断线横幅提示
 * 对应重构方案 §5.8.7
 *
 * 监听 eventBus 的 opponentDisconnected / opponentReconnected 事件
 * 显示宽限期倒计时，对手重连后自动消失
 */
export default function OpponentDisconnectBanner() {
  const [countdown, setCountdown] = useState<number | null>(null);

  useEffect(() => {
    const onDisconnect = (payload: { gracePeriodSeconds: number }) => {
      setCountdown(payload.gracePeriodSeconds);
    };
    const onReconnect = () => {
      setCountdown(null);
    };

    eventBus.on("opponentDisconnected" as never, onDisconnect as never);
    eventBus.on("opponentReconnected" as never, onReconnect as never);

    return () => {
      eventBus.off("opponentDisconnected" as never, onDisconnect as never);
      eventBus.off("opponentReconnected" as never, onReconnect as never);
    };
  }, []);

  // 本地秒级倒计时
  useEffect(() => {
    if (countdown === null || countdown <= 0) return;
    const t = setInterval(() => setCountdown((n) => (n !== null && n > 0 ? n - 1 : null)), 1000);
    return () => clearInterval(t);
  }, [countdown]);

  if (countdown === null) return null;

  return (
    <div className="absolute top-4 left-1/2 -translate-x-1/2 z-40 bg-yellow-500/90 text-black px-6 py-2 rounded-lg font-bold shadow-lg text-sm animate-pulse">
      对手已断线，等待重连 {countdown}s
    </div>
  );
}
