// opcgpro-vue/src/components/game/ReconnectOverlay.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { useRouter } from "vue-router";
import { useStore } from "@/composables/useStore";
import { useNetStore } from "@/store/netStore";

const router = useRouter();
const connState = useStore(useNetStore, (s) => s.connState);
const reconnectCountdown = useStore(useNetStore, (s) => s.reconnectCountdown);
const remaining = ref(0);
let timer: ReturnType<typeof setInterval> | null = null;

watch(
  [reconnectCountdown, connState],
  () => {
    if (timer) { clearInterval(timer); timer = null; }
    if (connState.value !== "reconnecting") return;
    remaining.value = reconnectCountdown.value;
    timer = setInterval(() => { remaining.value = Math.max(0, remaining.value - 1); }, 1000);
  },
  { immediate: true },
);

const visible = computed(() => connState.value === "reconnecting" || connState.value === "recovering");
</script>

<template>
  <Transition name="fade">
    <div
      v-if="visible"
      class="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/80 backdrop-blur-sm"
    >
      <div class="mb-4 h-12 w-12 animate-spin rounded-full border-4 border-orange-400 border-t-transparent" />
      <template v-if="connState === 'reconnecting'">
        <p class="text-xl font-bold text-white">连接已断开</p>
        <p class="mt-2 text-gray-400">{{ remaining > 0 ? `${remaining} 秒后重试...` : "正在重连..." }}</p>
      </template>
      <p v-else-if="connState === 'recovering'" class="text-xl font-bold text-white">正在恢复游戏状态...</p>
    </div>
  </Transition>

  <div
    v-if="connState === 'failed'"
    class="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/90"
  >
    <p class="mb-4 text-2xl font-bold text-red-400">连接失败</p>
    <p class="mb-6 text-gray-400">无法重新连接到服务器，游戏已结束</p>
    <button class="rounded-lg bg-orange-500 px-6 py-2 text-white transition-colors hover:bg-orange-400" @click="router.push('/home')">
      返回大厅
    </button>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active { transition: opacity 0.2s ease; }
.fade-enter-from,
.fade-leave-to { opacity: 0; }
</style>

// opcgpro-web/src/components/game/ReconnectOverlay.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { useNetStore } from "@/store/netStore";

/**
 * ReconnectOverlay — 断线重连全屏遮罩
 * 对应重构方案 §5.8.6
 *
 * 状态机:
 *   reconnecting → 显示倒计时 + 旋转动画
 *   recovering    → 显示"正在恢复游戏状态..."
 *   failed        → 显示"连接失败"，提供返回大厅按钮
 */
export default function ReconnectOverlay() {
  const router = useRouter();
  const { connState, reconnectCountdown } = useNetStore();
  const [remaining, setRemaining] = useState(0);

  // 收到新倒计时时启动本地秒级递减
  useEffect(() => {
    if (connState !== "reconnecting") return;
    setRemaining(reconnectCountdown);
    const t = setInterval(() => setRemaining((n) => Math.max(0, n - 1)), 1000);
    return () => clearInterval(t);
  }, [reconnectCountdown, connState]);

  const visible = connState === "reconnecting" || connState === "recovering";

  return (
    <AnimatePresence>
      {visible && (
        <motion.div
          className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/80 backdrop-blur-sm"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          {/* 旋转加载指示器 */}
          <div className="w-12 h-12 border-4 border-orange-400 border-t-transparent rounded-full animate-spin mb-4" />

          {connState === "reconnecting" && (
            <>
              <p className="text-white text-xl font-bold">连接已断开</p>
              <p className="text-gray-400 mt-2">
                {remaining > 0 ? `${remaining} 秒后重试...` : "正在重连..."}
              </p>
            </>
          )}

          {connState === "recovering" && (
            <p className="text-white text-xl font-bold">正在恢复游戏状态...</p>
          )}
        </motion.div>
      )}

      {connState === "failed" && (
        <motion.div
          className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/90"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
        >
          <p className="text-red-400 text-2xl font-bold mb-4">连接失败</p>
          <p className="text-gray-400 mb-6">无法重新连接到服务器，游戏已结束</p>
          <button
            onClick={() => router.push("/home")}
            className="bg-orange-500 text-white px-6 py-2 rounded-lg hover:bg-orange-400 transition-colors"
          >
            返回大厅
          </button>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
