// opcgpro-web/src/components/ui/MessageBox.tsx
"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useEffect, useState } from "react";
import GameOverlayPortal from "@/components/ui/GameOverlayPortal";

interface Message {
  id: number;
  text: string;
  type: "info" | "warn" | "error";
}

let msgId = 0;
const listeners: ((msg: Message) => void)[] = [];

export function showMessage(
  text: string,
  type: Message["type"] = "info"
): void {
  const msg: Message = { id: ++msgId, text, type };
  listeners.forEach((fn) => fn(msg));
}

export default function MessageBox() {
  const [messages, setMessages] = useState<Message[]>([]);

  useEffect(() => {
    const handler = (msg: Message) => {
      setMessages((prev) => [...prev, msg]);
      setTimeout(() => {
        setMessages((prev) => prev.filter((m) => m.id !== msg.id));
      }, 3000);
    };
    listeners.push(handler);
    return () => {
      const idx = listeners.indexOf(handler);
      if (idx >= 0) listeners.splice(idx, 1);
    };
  }, []);

  const colorMap = {
    info: "bg-gray-800 border-gray-600",
    warn: "bg-yellow-900 border-yellow-600",
    error: "bg-red-900 border-red-600",
  };

  return (
    <GameOverlayPortal>
      <div className="fixed top-4 left-1/2 -translate-x-1/2 z-50 flex flex-col gap-2 pointer-events-none">
        <AnimatePresence>
          {messages.map((msg) => (
            <motion.div
              key={msg.id}
              className={`px-4 py-2 rounded-lg border text-white text-sm shadow-lg ${colorMap[msg.type]}`}
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
            >
              {msg.text}
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
    </GameOverlayPortal>
  );
}

// opcgpro-vue/src/components/ui/MessageBox.vue
<script setup lang="ts">
// MessageBox 宿主 —— 订阅命令式内核 messageBus（@/components/ui/MessageBox.ts）渲染 toast。
// 挂在全局壳里一次即可（Phase 5b 起在 App.vue / 各页面顶层挂载）。
import { ref, onMounted, onUnmounted } from "vue";
import { messageBus, type MessageType } from "@/components/ui/MessageBox";

interface Toast {
  id: number;
  text: string;
  type: MessageType;
}

let seq = 0;
const toasts = ref<Toast[]>([]);

const colorMap: Record<MessageType, string> = {
  info: "bg-gray-800 border-gray-600",
  success: "bg-green-900 border-green-600",
  error: "bg-red-900 border-red-600",
};

function onShow({ text, type }: { text: string; type: MessageType }) {
  const id = ++seq;
  toasts.value.push({ id, text, type });
  setTimeout(() => {
    toasts.value = toasts.value.filter((t) => t.id !== id);
  }, 3000);
}

onMounted(() => messageBus.on("show", onShow));
onUnmounted(() => messageBus.off("show", onShow));
</script>

<template>
  <div
    class="pointer-events-none fixed left-1/2 top-4 z-50 flex -translate-x-1/2 flex-col gap-2"
  >
    <TransitionGroup name="toast">
      <div
        v-for="t in toasts"
        :key="t.id"
        :class="['rounded-lg border px-4 py-2 text-sm text-white shadow-lg', colorMap[t.type]]"
      >
        {{ t.text }}
      </div>
    </TransitionGroup>
  </div>
</template>

<style scoped>
.toast-enter-active,
.toast-leave-active {
  transition: all 0.2s ease;
}
.toast-enter-from,
.toast-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
