// opcgpro-vue/src/components/deck-editor/SearchResultPanel.vue
<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from "vue";
import { getAllCachedCards } from "@/data/CardLoader";
import { useStore } from "@/composables/useStore";
import { useDeckStore, FORMAT_RULES } from "@/store/deckStore";
import type { CardData } from "@/types/card";
import CardInfoPanel from "@/components/game/CardInfoPanel.vue";
import CardHoverPreview from "./CardHoverPreview.vue";
import type { HoverInfo } from "./CardHoverPreview";
import CardGridItem from "./CardGridItem.vue";

const HOVER_DELAY = 180;

const format = useStore(useDeckStore, (s) => s.format);
const gridColumns = useStore(useDeckStore, (s) => s.gridColumns);
const searchQuery = useStore(useDeckStore, (s) => s.searchQuery);
const filterColor = useStore(useDeckStore, (s) => s.filterColor);
const filterType = useStore(useDeckStore, (s) => s.filterType);
const filterProperty = useStore(useDeckStore, (s) => s.filterProperty);
const filterRarity = useStore(useDeckStore, (s) => s.filterRarity);
const filterSets = useStore(useDeckStore, (s) => s.filterSets);
const filterShowSub1 = useStore(useDeckStore, (s) => s.filterShowSub1);
const notice = useStore(useDeckStore, (s) => s.notice);
// 触发依赖：entries 变化时需要重算 getCount 显示
const entries = useStore(useDeckStore, (s) => s.entries);

const store = () => useDeckStore.getState();

const modal = ref<CardData | null>(null);
const hover = ref<HoverInfo | null>(null);
let hoverTimer: ReturnType<typeof setTimeout> | null = null;
let noticeTimer: ReturnType<typeof setTimeout> | null = null;

const isLeaderMode = computed(() => filterType.value === "Leader");

watch(notice, (n) => {
  if (!n || n.type !== "error") return;
  if (noticeTimer) clearTimeout(noticeTimer);
  noticeTimer = setTimeout(() => store().clearNotice(), 2000);
});

const results = computed(() => {
  const all = getAllCachedCards();
  const rule = FORMAT_RULES[format.value];
  const whitelist = isLeaderMode.value ? rule.leaderSetWhitelist : rule.mainSetWhitelist;
  const q = searchQuery.value.toLowerCase();
  return all.filter((card) => {
    const setCode = card.number.split("-")[0];
    if (whitelist && !whitelist.includes(setCode)) return false;
    if (filterSets.value.length > 0 && !filterSets.value.includes(setCode)) return false;
    if (!filterShowSub1.value && card.subscript === 1) return false;
    if (isLeaderMode.value && card.type !== "Leader") return false;
    if (!isLeaderMode.value && card.type === "Leader") return false;
    if (filterColor.value && !card.color.includes(filterColor.value)) return false;
    if (filterProperty.value && card.property !== filterProperty.value) return false;
    if (filterRarity.value && card.rarity !== filterRarity.value) return false;
    if (!isLeaderMode.value && filterType.value && card.type !== filterType.value) return false;
    if (q) {
      if (
        !card.name.toLowerCase().includes(q) &&
        !card.number.toLowerCase().includes(q) &&
        !card.keyWords.some((k) => k.toLowerCase().includes(q)) &&
        !card.effectText.toLowerCase().includes(q)
      ) return false;
    }
    return true;
  });
});

function getCount(number: string): number {
  void entries.value;
  return store().getCount(number);
}

function handleCardClick(card: CardData) {
  isLeaderMode.value ? store().setLeader(card) : store().addCard(card);
}
function handleMouseEnter(card: CardData, rect: DOMRect, currentSprite: string) {
  if (hoverTimer) clearTimeout(hoverTimer);
  hoverTimer = setTimeout(() => (hover.value = { card, rect, currentSprite }), HOVER_DELAY);
}
function handleMouseLeave() {
  if (hoverTimer) clearTimeout(hoverTimer);
  hover.value = null;
}
function onSpriteChange(card: CardData, sprite: string) {
  card.sprite = sprite;
  if (hover.value) hover.value = { ...hover.value, currentSprite: sprite };
}

onUnmounted(() => {
  if (hoverTimer) clearTimeout(hoverTimer);
  if (noticeTimer) clearTimeout(noticeTimer);
});
</script>

<template>
  <div class="result-root">
    <div class="result-head">
      <p class="kicker result-head__title">
        {{ isLeaderMode ? "选择领航卡" : "搜索结果" }}
        <span class="result-head__sub">· 共 {{ results.length }} 张</span>
      </p>
      <span class="mono faint result-head__cols">{{ gridColumns }} 列</span>
    </div>

    <Transition name="notice">
      <div v-if="notice?.type === 'error'" class="result-notice">
        <p>{{ notice.message }}</p>
      </div>
    </Transition>

    <div class="result-grid-wrap">
      <div v-if="results.length === 0" class="result-empty">
        <p class="mono result-empty__text">// 没有找到匹配的卡牌</p>
      </div>
      <div v-else class="result-grid" :style="{ gridTemplateColumns: `repeat(${gridColumns}, minmax(0, 1fr))` }">
        <div
          v-for="card in results"
          :key="card.number"
        >
          <CardGridItem
            :card="card"
            :deck-count="isLeaderMode ? 0 : getCount(card.number)"
            :is-leader-mode="isLeaderMode"
            @click="handleCardClick(card)"
            @right-click="modal = card"
            @mouse-enter="handleMouseEnter"
            @mouse-leave="handleMouseLeave"
            @sprite-change="(s) => onSpriteChange(card, s)"
          />
        </div>
      </div>
    </div>

    <CardHoverPreview v-if="hover" :info="hover" />
    <CardInfoPanel :card="modal" @close="modal = null" />
  </div>
</template>

<style scoped>
.result-root {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  font-family: var(--font-ui);
  color: var(--ink);
}

/* ── 头部：结果数 · 列数 ── */
.result-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 18px;
  border-bottom: 1px solid var(--line);
  flex-shrink: 0;
}
.result-head__title {
  font-size: 11px;
}
.result-head__sub {
  margin-left: 8px;
  font-family: var(--font-ui);
  text-transform: none;
  letter-spacing: 0;
  color: var(--ink-faint);
  font-size: 11px;
}
.result-head__cols {
  font-size: 10px;
  letter-spacing: 0.14em;
}

/* ── 通知 ── */
.result-notice {
  padding: 8px 14px;
  border-bottom: 1px solid color-mix(in srgb, var(--bad) 30%, transparent);
  background: color-mix(in srgb, var(--bad) 10%, transparent);
  font-size: 12px;
  color: var(--bad);
  text-align: center;
}
.notice-enter-active,
.notice-leave-active { transition: all 0.15s ease; }
.notice-enter-from,
.notice-leave-to     { opacity: 0; transform: translateY(-6px); }

/* ── 网格区 ── */
.result-grid-wrap {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding: 14px;
}
.result-empty {
  height: 12rem;
  display: flex;
  align-items: center;
  justify-content: center;
}
.result-empty__text {
  font-size: 12px;
  letter-spacing: 0.2em;
  color: var(--ink-faint);
  text-transform: uppercase;
  margin: 0;
}
.result-grid {
  display: grid;
  gap: 12px;
}
</style>

// opcgpro-web/src/components/deck-editor/SearchResultPanel.tsx
"use client";

import { useMemo, useState, useRef, useCallback, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import NextImage from "next/image";
import { getAllCachedCards } from "@/data/CardLoader";
import { useDeckStore, FORMAT_RULES } from "@/store/deckStore";
import type { CardData } from "@/types/card";
import CardInfoPanel from "@/components/game/CardInfoPanel";
import CardHoverPreview, { type HoverInfo, RARITY_STYLES } from "./CardHoverPreview";
import { useVirtualList } from "@/hooks/useVirtualList";

const HOVER_DELAY  = 180;   // 悬停多少毫秒后显示（避免划过时闪烁）
const CARD_WIDTH    = 72;   // w-16(64px) + gap
const CARD_HEIGHT   = 108;  // h-24(96px) + 名称行 + gap

// ── 主组件 ────────────────────────────────────────────────────────────────
export default function SearchResultPanel() {
  const { format, searchQuery, filterColor, filterType, filterProperty, filterRarity, filterSets, filterShowSub1, gridColumns, addCard, setLeader, getCount, notice, clearNotice } =
    useDeckStore();
  const [modal, setModal]     = useState<CardData | null>(null);   // 右键弹窗
  const [hover, setHover]     = useState<HoverInfo | null>(null);  // 悬停预览
  const hoverTimer            = useRef<ReturnType<typeof setTimeout> | null>(null);
  const noticeTimer           = useRef<ReturnType<typeof setTimeout> | null>(null);

  // error notice 2秒后自动清除
  useEffect(() => {
    if (!notice || notice.type !== "error") return;
    if (noticeTimer.current) clearTimeout(noticeTimer.current);
    noticeTimer.current = setTimeout(() => clearNotice(), 2000);
    return () => { if (noticeTimer.current) clearTimeout(noticeTimer.current); };
  }, [notice, clearNotice]);

  const isLeaderMode = filterType === "Leader";

  const results = useMemo(() => {
    const all = getAllCachedCards();
    const rule = FORMAT_RULES[format];
    const whitelist = isLeaderMode ? rule.leaderSetWhitelist : rule.mainSetWhitelist;
    return all.filter((card) => {
      const setCode = card.number.split("-")[0];
      // 格式卡集白名单过滤（Unrestricted 时为 null = 不限）
      if (whitelist && !whitelist.includes(setCode)) return false;
      // 用户手动选的弹数筛选（多选；空数组 = 不过滤）
      if (filterSets.length > 0 && !filterSets.includes(setCode)) return false;
      // 角标=1 默认隐藏（旧环境/早期版本）
      if (!filterShowSub1 && card.subscript === 1) return false;
      if (isLeaderMode && card.type !== "Leader") return false;
      if (!isLeaderMode && card.type === "Leader") return false;
      if (filterColor && !card.color.includes(filterColor)) return false;
      if (filterProperty && card.property !== filterProperty) return false;
      if (filterRarity && card.rarity !== filterRarity) return false;
      if (!isLeaderMode && filterType && card.type !== filterType) return false;
      if (searchQuery) {
        const q = searchQuery.toLowerCase();
        if (
          !card.name.toLowerCase().includes(q) &&
          !card.number.toLowerCase().includes(q) &&
          !card.keyWords.some((k) => k.toLowerCase().includes(q)) &&
          !card.effectText.toLowerCase().includes(q)
        ) return false;
      }
      return true;
    });
  }, [format, searchQuery, filterColor, filterType, filterProperty, filterRarity, filterSets, filterShowSub1, isLeaderMode]);

  // 虚拟网格列表
  const {
    containerRef: scrollRef,
    totalHeight,
    visibleItems,
  } = useVirtualList({
    itemCount: results.length,
    itemHeight: CARD_HEIGHT,
    rowWidth: CARD_WIDTH,
    columns: gridColumns,
    gap: 8,
    overscan: 2,
  });

  const handleCardClick = (card: CardData) =>
    isLeaderMode ? setLeader(card) : addCard(card);

  // 延迟显示预览，鼠标快速划过时不触发
  const handleMouseEnter = useCallback((card: CardData, rect: DOMRect, currentSprite: string) => {
    if (hoverTimer.current) clearTimeout(hoverTimer.current);
    hoverTimer.current = setTimeout(() => setHover({ card, rect, currentSprite }), HOVER_DELAY);
  }, []);

  const handleMouseLeave = useCallback(() => {
    if (hoverTimer.current) clearTimeout(hoverTimer.current);
    setHover(null);
  }, []);

  return (
    <div className="flex flex-col h-full">
      {/* 工具栏 */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-gray-800 shrink-0">
        <p className="text-gray-500 text-xs">
          {isLeaderMode ? "选择领航卡" : "搜索结果"} · 共 {results.length} 张
        </p>
      </div>

      {/* 颜色不符提示 */}
      <AnimatePresence>
        {notice?.type === "error" && (
          <motion.div
            initial={{ opacity: 0, y: -6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -6 }}
            transition={{ duration: 0.15 }}
            className="px-3 py-1.5 bg-red-900/80 border-b border-red-800 shrink-0"
          >
            <p className="text-red-300 text-xs text-center">{notice.message}</p>
          </motion.div>
        )}
      </AnimatePresence>

      {/* 虚拟滚动卡片网格 */}
      <div
        ref={scrollRef}
        className="flex-1 overflow-y-auto p-3"
      >
        {results.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-48 gap-2">
            <p className="text-gray-600 text-sm">没有找到匹配的卡牌</p>
          </div>
        ) : (
          <div className="relative" style={{ height: totalHeight }}>
            {visibleItems.map(({ index, row, col }) => {
              const card = results[index];
              if (!card) return null;
              return (
                <div
                  key={card.number}
                  className="absolute"
                  style={{
                    top: row * (CARD_HEIGHT + 8),
                    left: col * (CARD_WIDTH + 8),
                    width: CARD_WIDTH,
                    height: CARD_HEIGHT,
                  }}
                >
                  <CardGridItem
                    card={card}
                    deckCount={isLeaderMode ? 0 : getCount(card.number)}
                    isLeaderMode={isLeaderMode}
                    onClick={() => handleCardClick(card)}
                    onRightClick={(e) => { e.preventDefault(); setModal(card); }}
                    onMouseEnter={handleMouseEnter}
                    onMouseLeave={handleMouseLeave}
                    onSpriteChange={(sprite) => {
                      card.sprite = sprite;
                      setHover((prev) => prev ? { ...prev, currentSprite: sprite } : null);
                    }}
                  />
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* 悬停大图预览（fixed 定位，不受 overflow 裁剪） */}
      <AnimatePresence>
        {hover && <CardHoverPreview info={hover} />}
      </AnimatePresence>

      {/* 右键弹窗 */}
      <CardInfoPanel card={modal} onClose={() => setModal(null)} />
    </div>
  );
}

// ── 单张卡片格子 ──────────────────────────────────────────────────────────

interface CardGridItemProps {
  card: CardData;
  deckCount: number;
  isLeaderMode: boolean;
  onClick: () => void;
  onRightClick: (e: React.MouseEvent) => void;
  onMouseEnter: (card: CardData, rect: DOMRect, currentSprite: string) => void;
  onMouseLeave: () => void;
  onSpriteChange: (sprite: string) => void;
}

function CardGridItem({
  card, deckCount, isLeaderMode, onClick, onRightClick, onMouseEnter, onMouseLeave, onSpriteChange,
}: CardGridItemProps) {
  const isFull    = !isLeaderMode && deckCount >= 4;
  const hasInDeck = deckCount > 0;

  const sprites   = card.sprites?.length ? card.sprites : [card.sprite ?? "/sprites/CardBack.png"];
  const hasAlts   = sprites.length > 1;
  const [spriteIdx, setSpriteIdx] = useState(sprites.length - 1);
  const [imgFailed, setImgFailed] = useState(false);
  const currentSrc = imgFailed ? "/sprites/CardBack.png" : (sprites[spriteIdx] ?? "/sprites/CardBack.png");

  // 初始化时同步默认异画的 sprite 到 card 对象，确保添加卡牌时使用正确的异画
  useEffect(() => {
    const initialSprite = sprites[sprites.length - 1];
    if (initialSprite && card.sprite !== initialSprite) {
      card.sprite = initialSprite;
    }
    // 仅首次运行
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const goPrev = (e: React.MouseEvent) => {
    e.stopPropagation();
    setImgFailed(false);
    const next = (spriteIdx - 1 + sprites.length) % sprites.length;
    setSpriteIdx(next);
    onSpriteChange(sprites[next]);
  };
  const goNext = (e: React.MouseEvent) => {
    e.stopPropagation();
    setImgFailed(false);
    const next = (spriteIdx + 1) % sprites.length;
    setSpriteIdx(next);
    onSpriteChange(sprites[next]);
  };

  return (
    <motion.div
      layout
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      transition={{ duration: 0.15 }}
      className="group flex flex-col items-center gap-1 transform-gpu backface-hidden"
      onMouseEnter={(e) => onMouseEnter(card, e.currentTarget.getBoundingClientRect(), currentSrc)}
      onMouseLeave={onMouseLeave}
    >
      <div
        className={`relative w-16 h-24 rounded-lg overflow-hidden select-none border-2 transition-all
          ${isFull
            ? "border-red-800 opacity-50 cursor-not-allowed"
            : isLeaderMode
              ? "border-yellow-600 hover:border-yellow-400 hover:scale-105 cursor-pointer"
              : hasInDeck
                ? "border-orange-500 hover:scale-105 cursor-pointer"
                : "border-gray-700 hover:border-gray-400 hover:scale-105 cursor-pointer"
          }`}
        onClick={isFull ? undefined : onClick}
        onContextMenu={onRightClick}
      >
        <NextImage
          src={currentSrc}
          alt={card.name}
          fill
          sizes="64px"
          className="object-cover"
          draggable={false}
          onError={() => setImgFailed(true)}
        />

        {/* 异画切换箭头（仅有多版本时显示） */}
        {hasAlts && (
          <>
            <button
              className="absolute left-0 top-0 bottom-0 w-4 flex items-center justify-center
                         bg-black/50 hover:bg-black/75 text-white text-xs z-10
                         opacity-0 group-hover:opacity-100 transition-opacity"
              style={{ fontSize: 14 }}
              onClick={goPrev}
              title="上一版本"
            >‹</button>
            <button
              className="absolute right-0 top-0 bottom-0 w-4 flex items-center justify-center
                         bg-black/50 hover:bg-black/75 text-white text-xs z-10
                         opacity-0 group-hover:opacity-100 transition-opacity"
              style={{ fontSize: 14 }}
              onClick={goNext}
              title="下一版本"
            >›</button>
          </>
        )}

        {/* 异画版本指示点 */}
        {hasAlts && (
          <div className="absolute bottom-0 left-0 right-0 flex justify-center gap-0.5 pb-0.5 z-10">
            {sprites.map((_, i) => (
              <span
                key={i}
                className={`block w-1 h-1 rounded-full ${i === spriteIdx ? "bg-white" : "bg-white/40"}`}
              />
            ))}
          </div>
        )}

        {/* 费用（领袖卡不显示） */}
        {card.type !== "Leader" && (
          <div className="absolute top-0.5 left-0.5 bg-black/70 text-white text-[9px] font-bold px-1 rounded">
            {card.cost}
          </div>
        )}
        {/* 稀有度角标 */}
        {card.rarity && (
          <div className={`absolute top-0.5 right-0.5 text-[8px] font-bold px-1 rounded ${RARITY_STYLES[card.rarity] ?? "bg-gray-700 text-white"}`}>
            {card.rarity}
          </div>
        )}
        {/* 威力 */}
        {card.power > 0 && (
          <div className="absolute bottom-0.5 right-0.5 bg-black/70 text-white text-[9px] font-bold px-1 rounded">
            {(card.power / 1000).toFixed(0)}k
          </div>
        )}
        {/* 角标 */}
        {card.subscript > 0 && (
          <div className="absolute bottom-0.5 left-0.5 bg-black/70 text-yellow-400 text-[8px] font-bold px-1 rounded">
            {card.subscript}
          </div>
        )}
        {/* 数量徽章 */}
        {hasInDeck && !isLeaderMode && (
          <div className="absolute top-0.5 right-0.5 w-4 h-4 bg-orange-500 rounded-full flex items-center justify-center">
            <span className="text-white text-[9px] font-bold leading-none">{deckCount}</span>
          </div>
        )}
        {/* 已满遮罩 */}
        {isFull && (
          <div className="absolute inset-0 flex items-center justify-center">
            <span className="text-red-400 text-xs font-bold bg-black/60 px-1 rounded">已满</span>
          </div>
        )}
      </div>

      <p className="text-gray-400 text-[10px] text-center truncate w-full leading-tight px-0.5">
        {card.name}
      </p>
    </motion.div>
  );
}
