// opcgpro-web/src/components/home/FriendlyRoomPanel.tsx
"use client";

import { useEffect, useState } from "react";
import { useNetStore } from "@/store/netStore";
import { HomeRequest } from "@/net/HomeProtocol";
import { loadAllDecks, getSpriteMap, type SavedDeck } from "@/data/DeckMapper";

export default function FriendlyRoomPanel() {
  const room    = useNetStore((s) => s.friendlyRoom);
  const account = useNetStore((s) => s.account);
  const [decks, setDecks]     = useState<Record<string, SavedDeck>>({});
  const [picking, setPicking] = useState(false);

  useEffect(() => { setDecks(loadAllDecks()); }, []);

  if (!room) return null;

  const myIndex  = room.players.findIndex((p) => p.account === account);
  const oppIndex = myIndex === 0 ? 1 : 0;
  const me  = room.players[myIndex];
  const opp = room.players[oppIndex];
  const myScore  = room.scores[myIndex] ?? 0;
  const oppScore = room.scores[oppIndex] ?? 0;

  const selectDeck = (name: string) => {
    const saved = loadAllDecks()[name];
    if (!saved) return;
    const cards = [saved.leader, ...saved.cards].join("\n");
    if (typeof window !== "undefined") {
      sessionStorage.setItem("grandumi_spriteMap", JSON.stringify(getSpriteMap(name)));
    }
    HomeRequest.friendlySelectDeck(cards, name);
    setPicking(false);
  };

  const toggleReady = () => HomeRequest.friendlyReady(!me?.ready);
  const leave = () => HomeRequest.friendlyLeave();

  const deckEntries = Object.entries(decks);

  return (
    <div className="flex h-screen flex-col items-center justify-center bg-gray-950 p-8 gap-6">
      <h2 className="text-white font-bold text-2xl">友谊战房间</h2>

      {/* 比分 */}
      <div className="flex items-center gap-4">
        <span className="text-sm text-gray-400 truncate max-w-[8rem] text-right">{me?.name ?? "我"}</span>
        <span className="text-3xl font-black text-orange-400">{myScore} : {oppScore}</span>
        <span className="text-sm text-gray-400 truncate max-w-[8rem]">{opp?.name ?? "对方"}</span>
      </div>

      {/* 双方状态卡 */}
      <div className="flex gap-6">
        <PlayerCard title="我"   name={me?.name}  deckName={me?.deckName}  ready={me?.ready}  mine />
        <PlayerCard title="对手" name={opp?.name} deckName={opp?.deckName} ready={opp?.ready} />
      </div>

      {/* 操作区 */}
      <div className="flex flex-col items-center gap-3 w-full max-w-sm">
        <button
          onClick={() => setPicking((v) => !v)}
          className="w-full py-2 rounded-lg bg-gray-800 border border-gray-700 text-white text-sm hover:border-orange-500 transition-colors"
        >
          {me?.deckName ? `已选：${me.deckName}（点击更换）` : "选择卡组"}
        </button>

        {picking && (
          <div className="w-full max-h-48 overflow-y-auto flex flex-col gap-1 bg-gray-900 border border-gray-800 rounded-lg p-2">
            {deckEntries.length === 0 ? (
              <p className="text-gray-600 text-xs text-center py-3">还没有卡组，去「卡组」面板创建</p>
            ) : (
              deckEntries.map(([name, d]) => (
                <button
                  key={name}
                  onClick={() => selectDeck(name)}
                  className="flex items-center gap-2 px-2 py-1.5 rounded hover:bg-gray-800 text-left"
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={d.leaderSprite || "/sprites/CardBack.png"}
                    alt={d.leaderName}
                    className="w-7 h-10 object-cover rounded border border-gray-700 shrink-0"
                    onError={(e) => { (e.target as HTMLImageElement).src = "/sprites/CardBack.png"; }}
                  />
                  <div className="min-w-0">
                    <p className="text-white text-xs truncate">{name}</p>
                    <p className="text-gray-500 text-[10px] truncate">{d.leaderName}</p>
                  </div>
                </button>
              ))
            )}
          </div>
        )}

        <button
          onClick={toggleReady}
          disabled={!me?.deckName}
          className={`w-full py-2.5 rounded-xl font-bold text-sm transition-all ${
            !me?.deckName
              ? "bg-gray-800 text-gray-600 cursor-not-allowed"
              : me?.ready
                ? "bg-green-600 hover:bg-green-500 text-white"
                : "bg-orange-500 hover:bg-orange-400 text-white"
          }`}
        >
          {me?.ready ? "✓ 已准备（点击取消）" : "准备"}
        </button>

        {me?.ready && opp?.ready && (
          <p className="text-green-400 text-xs">双方已准备，即将开始对战…</p>
        )}

        <button
          onClick={leave}
          className="text-gray-500 hover:text-red-400 text-xs transition-colors mt-2"
        >
          退出房间
        </button>
      </div>
    </div>
  );
}

function PlayerCard({ title, name, deckName, ready, mine }: {
  title: string; name?: string; deckName?: string | null; ready?: boolean; mine?: boolean;
}) {
  return (
    <div className={`w-44 rounded-xl border-2 p-4 flex flex-col items-center gap-2 ${
      mine ? "border-orange-500/60 bg-orange-500/5" : "border-gray-700 bg-gray-900"
    }`}>
      <span className="text-gray-500 text-[10px]">{title}</span>
      <p className="text-white font-bold text-sm truncate w-full text-center">{name ?? "?"}</p>
      <p className="text-gray-400 text-xs truncate w-full text-center">{deckName ?? "未选卡组"}</p>
      <span className={`text-[11px] font-bold ${ready ? "text-green-400" : "text-gray-600"}`}>
        {ready ? "已准备" : "未准备"}
      </span>
    </div>
  );
}

// opcgpro-vue/src/components/home/FriendlyRoomPanel.vue
<script setup lang="ts">
import { ref, onMounted, computed } from "vue";
import { useStore } from "@/composables/useStore";
import { useNetStore } from "@/store/netStore";
import { HomeRequest } from "@/net/HomeProtocol";
import { loadAllDecks, type SavedDeck } from "@/data/DeckMapper";

const room = useStore(useNetStore, (s) => s.friendlyRoom);
const account = useStore(useNetStore, (s) => s.account);
const decks = ref<Record<string, SavedDeck>>({});
const picking = ref(false);

onMounted(() => { decks.value = loadAllDecks(); });

const myIndex = computed(() => room.value?.players.findIndex((p) => p.account === account.value) ?? -1);
const oppIndex = computed(() => (myIndex.value === 0 ? 1 : 0));
const me = computed(() => room.value?.players[myIndex.value]);
const opp = computed(() => room.value?.players[oppIndex.value]);
const myScore = computed(() => room.value?.scores[myIndex.value] ?? 0);
const oppScore = computed(() => room.value?.scores[oppIndex.value] ?? 0);

function selectDeck(name: string) {
  const saved = loadAllDecks()[name];
  if (!saved) return;
  const cards = [saved.leader, ...saved.cards].join("\n");
  HomeRequest.friendlySelectDeck(cards, name);
  picking.value = false;
}

function toggleReady() { HomeRequest.friendlyReady(!me.value?.ready); }
function leave() { HomeRequest.friendlyLeave(); }
</script>

<template>
  <div v-if="room" class="flex h-screen flex-col items-center justify-center gap-6 bg-gray-950 p-8">
    <h2 class="text-2xl font-bold text-white">友谊战房间</h2>

    <div class="flex items-center gap-4">
      <span class="max-w-[8rem] truncate text-right text-sm text-gray-400">{{ me?.name ?? "我" }}</span>
      <span class="text-3xl font-black text-orange-400">{{ myScore }} : {{ oppScore }}</span>
      <span class="max-w-[8rem] truncate text-sm text-gray-400">{{ opp?.name ?? "对方" }}</span>
    </div>

    <div class="flex gap-6">
      <div class="flex w-44 flex-col items-center gap-2 rounded-xl border-2 border-orange-500/60 bg-orange-500/5 p-4">
        <span class="text-[10px] text-gray-500">我</span>
        <p class="w-full truncate text-center text-sm font-bold text-white">{{ me?.name ?? "?" }}</p>
        <p class="w-full truncate text-center text-xs text-gray-400">{{ me?.deckName ?? "未选卡组" }}</p>
        <span :class="['text-[11px] font-bold', me?.ready ? 'text-green-400' : 'text-gray-600']">
          {{ me?.ready ? "已准备" : "未准备" }}
        </span>
      </div>
      <div class="flex w-44 flex-col items-center gap-2 rounded-xl border-2 border-gray-700 bg-gray-900 p-4">
        <span class="text-[10px] text-gray-500">对手</span>
        <p class="w-full truncate text-center text-sm font-bold text-white">{{ opp?.name ?? "?" }}</p>
        <p class="w-full truncate text-center text-xs text-gray-400">{{ opp?.deckName ?? "未选卡组" }}</p>
        <span :class="['text-[11px] font-bold', opp?.ready ? 'text-green-400' : 'text-gray-600']">
          {{ opp?.ready ? "已准备" : "未准备" }}
        </span>
      </div>
    </div>

    <div class="flex w-full max-w-sm flex-col items-center gap-3">
      <button
        class="w-full rounded-lg border border-gray-700 bg-gray-800 py-2 text-sm text-white transition-colors hover:border-orange-500"
        @click="picking = !picking"
      >
        {{ me?.deckName ? `已选：${me.deckName}（点击更换）` : "选择卡组" }}
      </button>

      <div
        v-if="picking"
        class="flex w-full max-h-48 flex-col gap-1 overflow-y-auto rounded-lg border border-gray-800 bg-gray-900 p-2"
      >
        <p v-if="Object.keys(decks).length === 0" class="py-3 text-center text-xs text-gray-600">
          还没有卡组，去「卡组」面板创建
        </p>
        <button
          v-for="(d, name) in decks"
          :key="name"
          class="flex items-center gap-2 rounded px-2 py-1.5 text-left hover:bg-gray-800"
          @click="selectDeck(name)"
        >
          <img
            :src="d.leaderSprite || '/sprites/CardBack.png'"
            :alt="d.leaderName"
            class="h-10 w-7 shrink-0 rounded border border-gray-700 object-cover"
            @error="(e) => ((e.target as HTMLImageElement).src = '/sprites/CardBack.png')"
          />
          <div class="min-w-0">
            <p class="truncate text-xs text-white">{{ name }}</p>
            <p class="truncate text-[10px] text-gray-500">{{ d.leaderName }}</p>
          </div>
        </button>
      </div>

      <button
        :disabled="!me?.deckName"
        :class="[
          'w-full rounded-xl py-2.5 text-sm font-bold transition-all',
          !me?.deckName
            ? 'cursor-not-allowed bg-gray-800 text-gray-600'
            : me?.ready
              ? 'bg-green-600 text-white hover:bg-green-500'
              : 'bg-orange-500 text-white hover:bg-orange-400',
        ]"
        @click="toggleReady"
      >
        {{ me?.ready ? "✓ 已准备（点击取消）" : "准备" }}
      </button>

      <p v-if="me?.ready && opp?.ready" class="text-xs text-green-400">双方已准备，即将开始对战…</p>

      <button class="mt-2 text-xs text-gray-500 transition-colors hover:text-red-400" @click="leave">
        退出房间
      </button>
    </div>
  </div>
</template>
