// opcgpro-web/src/components/home/MainPanel.tsx
"use client";

import { useState, useRef, useEffect, type PointerEvent as ReactPointerEvent } from "react";
import NextImage from "next/image";
import LobbyPanel from "./LobbyPanel";
import DeckChoosePanel from "./DeckChoosePanel";
import PlayerListPanel from "./PlayerListPanel";
import InviteNotifyOverlay from "./InviteNotifyOverlay";
import FriendlyRoomPanel from "./FriendlyRoomPanel";
import HistoryPanel from "./HistoryPanel";
import NetStatePanel from "@/components/ui/NetStatePanel";
import { useNetStore } from "@/store/netStore";
import { getAllCachedCards, loadCardSet } from "@/data/CardLoader";
import { loadAllDecks } from "@/data/DeckMapper";
import { DEFAULT_SEARCH_SETS } from "@/data/cardSets";
import type { CardData } from "@/types/card";
import Modal from "@/components/ui/Modal";
import { thumbSrc } from "@/lib/sprite";
import { useVirtualList } from "@/hooks/useVirtualList";

type View = "lobby" | "deck" | "history";

const AVATAR_KEY = "grandumi_avatar";

// 从缓存中找一个名为"路飞"的领航卡作为默认头像
function getDefaultAvatar(): string {
  if (typeof window === "undefined") return "";
  const all = getAllCachedCards();
  const luffy = all.find(
    (c) => c.type === "Leader" && c.name.includes("路飞")
  );
  return luffy?.sprite ?? "";
}

function loadAvatar(): string {
  if (typeof window === "undefined") return "";
  return localStorage.getItem(AVATAR_KEY) || getDefaultAvatar();
}

function PlayerAvatar() {
  const playerName = useNetStore((s) => s.playerName);
  const account = useNetStore((s) => s.account);
  const setPlayerName = useNetStore((s) => s.setPlayerName);

  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const [avatarSrc, setAvatarSrc] = useState("");
  const [showPicker, setShowPicker] = useState(false);

  useEffect(() => {
    setAvatarSrc(loadAvatar());
  }, []);

  const startEdit = () => {
    setDraft(playerName);
    setEditing(true);
  };

  useEffect(() => {
    if (editing) inputRef.current?.focus();
  }, [editing]);

  const confirm = () => {
    const name = draft.trim();
    if (!name) { setEditing(false); return; }
    setPlayerName(name);
    if (typeof window !== "undefined" && account) {
      localStorage.setItem(`grandumi_nick_${account}`, name);
    }
    setEditing(false);
  };

  const cancel = () => setEditing(false);

  const handleSelectAvatar = (card: CardData) => {
    const sprite = card.sprites?.length
      ? card.sprites[card.sprites.length - 1]
      : card.sprite ?? "";
    setAvatarSrc(sprite);
    localStorage.setItem(AVATAR_KEY, sprite);
    setShowPicker(false);
  };

  return (
    <>
      {editing ? (
        <div className="w-14 flex flex-col items-center gap-1 px-1">
          <input
            ref={inputRef}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") confirm();
              if (e.key === "Escape") cancel();
            }}
            onBlur={confirm}
            maxLength={16}
            className="w-full bg-gray-800 text-white text-[10px] rounded px-1 py-0.5 outline-none border border-orange-500 text-center"
          />
          <span className="text-gray-600 text-[8px]">Enter确认</span>
        </div>
      ) : (
        <div className="flex flex-col items-center gap-0.5 mb-1">
          {/* 头像 */}
          <button
            onClick={() => setShowPicker(true)}
            className="relative w-10 h-10 rounded-full overflow-hidden border-2 border-gray-700 hover:border-orange-500 transition-colors bg-gray-800 shrink-0"
            title="点击更换头像"
          >
            {avatarSrc ? (
              <NextImage
                src={avatarSrc}
                alt="头像"
                fill
                sizes="40px"
                className="object-cover object-top rounded-full"
                style={{ transform: "scale(1.1)" }}
                draggable={false}
                onError={() => setAvatarSrc("")}
              />
            ) : (
              <span className="text-white text-xs font-bold">
                {playerName ? playerName[0].toUpperCase() : "?"}
              </span>
            )}
          </button>
          {/* 昵称 */}
          <button
            onClick={startEdit}
            title="点击修改昵称"
            className="text-gray-500 hover:text-gray-300 text-[9px] truncate w-14 text-center transition-colors"
          >
            {playerName || "未知"}
          </button>
        </div>
      )}

      {/* 头像选择弹窗 */}
      <AvatarPicker
        open={showPicker}
        onClose={() => setShowPicker(false)}
        onSelect={handleSelectAvatar}
        current={avatarSrc}
      />
    </>
  );
}

// ── 头像选择器 ──────────────────────────────────────────────────────────────

function AvatarPicker({
  open,
  onClose,
  onSelect,
  current,
}: {
  open: boolean;
  onClose: () => void;
  onSelect: (card: CardData) => void;
  current: string;
}) {
  const [leaders, setLeaders] = useState<CardData[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!open) return;
    async function load() {
      setLoading(true);
      const allCached = getAllCachedCards();
      if (allCached.length === 0) {
        // 尚未加载过，先加载默认卡集
        for (const setName of DEFAULT_SEARCH_SETS) {
          await loadCardSet(setName).catch(() => {});
        }
      }
      const all = getAllCachedCards();
      setLeaders(all.filter((c) => c.type === "Leader"));
      setLoading(false);
    }
    load();
  }, [open]);

  return (
    <Modal open={open} onClose={onClose} title="选择头像">
      <p className="text-gray-500 text-[10px] mb-2">所有领航卡</p>
      {loading ? (
        <p className="text-gray-600 text-xs text-center py-8">加载中...</p>
      ) : (
        <AvatarGrid leaders={leaders} current={current} onSelect={onSelect} />
      )}
    </Modal>
  );
}

// 头像网格：虚拟滚动 + 缩略图 + 懒加载，避免一次性请求全部领航卡原图拖垮服务器。
// 单独组件，仅在 Modal 打开时挂载，确保 useVirtualList 正确绑定到滚动容器。
const AVATAR_ITEM = 56; // 单元 56px（w-14/h-14）
const AVATAR_GAP = 8;   // gap-2

function AvatarGrid({
  leaders,
  current,
  onSelect,
}: {
  leaders: CardData[];
  current: string;
  onSelect: (card: CardData) => void;
}) {
  const { containerRef, totalHeight, visibleItems } = useVirtualList({
    itemCount: leaders.length,
    itemHeight: AVATAR_ITEM,
    rowWidth: AVATAR_ITEM,
    columns: 5,
    gap: AVATAR_GAP,
  });

  return (
    <div ref={containerRef} className="h-80 overflow-y-auto">
      <div style={{ position: "relative", height: totalHeight }}>
        {visibleItems.map(({ index, row, col }) => {
          const card = leaders[index];
          if (!card) return null;
          const sprite = card.sprites?.length
            ? card.sprites[card.sprites.length - 1]
            : card.sprite ?? "";
          const isCurrent = sprite === current;
          return (
            <button
              key={card.number}
              onClick={() => onSelect(card)}
              style={{
                position: "absolute",
                top: row * (AVATAR_ITEM + AVATAR_GAP),
                left: col * (AVATAR_ITEM + AVATAR_GAP),
                width: AVATAR_ITEM,
                height: AVATAR_ITEM,
              }}
              className={`overflow-hidden rounded-full border-2 transition-all ${
                isCurrent
                  ? "border-orange-500 ring-2 ring-orange-500/40"
                  : "border-gray-700 hover:border-gray-400"
              }`}
              title={card.name}
            >
              {/* 用缩略图（约原图 15%）+ 原生懒加载；缩略图缺失则回退原图 */}
              <img
                src={thumbSrc(sprite)}
                alt={card.name}
                loading="lazy"
                decoding="async"
                draggable={false}
                className="h-full w-full object-cover object-top"
                style={{ transform: "scale(1.1)" }}
                onError={(e) => {
                  const img = e.currentTarget;
                  if (img.src.includes("-thumb/") && sprite) img.src = sprite;
                }}
              />
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ── 在线人数徽标（可拖动，避免与聊天发送键重叠；位置持久化到 localStorage）────────────

const ONLINE_BADGE_POS_KEY = "grandumi_online_badge_pos";

function OnlineCountBadge({ onClick }: { onClick: () => void }) {
  const onlineCount = useNetStore((s) => s.onlineCount);
  const [pos, setPos] = useState<{ x: number; y: number } | null>(null);
  const btnRef = useRef<HTMLButtonElement>(null);
  const dragRef = useRef<{ startX: number; startY: number; baseX: number; baseY: number; moved: boolean } | null>(null);
  const lastPosRef = useRef<{ x: number; y: number } | null>(null);

  // 恢复上次拖到的位置
  useEffect(() => {
    try {
      const saved = localStorage.getItem(ONLINE_BADGE_POS_KEY);
      if (saved) setPos(JSON.parse(saved));
    } catch {}
  }, []);

  const onPointerDown = (e: ReactPointerEvent<HTMLButtonElement>) => {
    const rect = btnRef.current?.getBoundingClientRect();
    if (!rect) return;
    dragRef.current = { startX: e.clientX, startY: e.clientY, baseX: rect.left, baseY: rect.top, moved: false };
    btnRef.current?.setPointerCapture(e.pointerId);
  };

  const onPointerMove = (e: ReactPointerEvent<HTMLButtonElement>) => {
    const d = dragRef.current;
    if (!d) return;
    const dx = e.clientX - d.startX;
    const dy = e.clientY - d.startY;
    // 小于阈值视为点击抖动，不进入拖动
    if (!d.moved && Math.abs(dx) < 4 && Math.abs(dy) < 4) return;
    d.moved = true;
    const bw = btnRef.current?.offsetWidth ?? 0;
    const bh = btnRef.current?.offsetHeight ?? 0;
    const x = Math.min(Math.max(0, d.baseX + dx), window.innerWidth - bw);
    const y = Math.min(Math.max(0, d.baseY + dy), window.innerHeight - bh);
    const np = { x, y };
    lastPosRef.current = np;
    setPos(np);
  };

  const onPointerUp = (e: ReactPointerEvent<HTMLButtonElement>) => {
    const d = dragRef.current;
    dragRef.current = null;
    try { btnRef.current?.releasePointerCapture(e.pointerId); } catch {}
    if (!d) return;
    if (!d.moved) {
      onClick(); // 未拖动 → 视为点击，打开在线玩家列表
    } else if (lastPosRef.current) {
      try { localStorage.setItem(ONLINE_BADGE_POS_KEY, JSON.stringify(lastPosRef.current)); } catch {}
    }
  };

  return (
    <button
      ref={btnRef}
      type="button"
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      title="查看在线玩家（可拖动）"
      style={pos ? { position: "fixed", left: pos.x, top: pos.y } : undefined}
      className={`${pos ? "" : "absolute bottom-3 right-4"} z-30 flex items-center gap-1.5 bg-gray-900/80 border border-gray-800 hover:border-green-600 rounded-full px-3 py-1 text-xs backdrop-blur-sm transition-colors cursor-grab active:cursor-grabbing touch-none select-none`}
    >
      <span className="w-2 h-2 rounded-full bg-green-400" />
      <span className="text-gray-300">
        在线 <span className="text-green-400 font-bold">{onlineCount}</span>
      </span>
    </button>
  );
}

const SELECTED_DECK_KEY = "grandumi_selected_deck";

export default function MainPanel() {
  const [view, setView] = useState<View>("lobby");
  const [showPlayerList, setShowPlayerList] = useState(false);
  const setGlobalDeck = useNetStore((s) => s.setSelectedDeck);
  const friendlyRoom = useNetStore((s) => s.friendlyRoom);

  // 启动时恢复已保存的卡组选择到全局 store
  // 直接从 SavedDeck 构建卡组字符串，不依赖卡牌缓存（缓存可能尚未加载）
  useEffect(() => {
    const name = localStorage.getItem(SELECTED_DECK_KEY);
    if (!name) return;
    const allDecks = loadAllDecks();
    const saved = allDecks[name];
    if (!saved) return;
    setGlobalDeck({
      name,
      leader: saved.leader,
      leaderName: saved.leaderName,
      cards: [saved.leader, ...saved.cards].join("\n"),
    });
  }, []);

  // 进入友谊战房间后，大厅整体切换为房间界面
  if (friendlyRoom) {
    return (
      <>
        <FriendlyRoomPanel />
        <InviteNotifyOverlay />
      </>
    );
  }

  return (
    <div
      className="flex h-screen bg-gray-950"
      style={{
        paddingTop: "env(safe-area-inset-top)",
        paddingLeft: "env(safe-area-inset-left)",
        paddingRight: "env(safe-area-inset-right)",
        paddingBottom: "env(safe-area-inset-bottom)",
      }}
    >
      {/* 侧边导航 */}
      <nav className="w-16 bg-gray-900 border-r border-gray-800 flex flex-col items-center py-4 gap-3">
        <PlayerAvatar />
        <button
          onClick={() => setView("lobby")}
          className={`w-10 h-10 rounded-xl text-xs font-bold transition-colors ${view === "lobby" ? "bg-orange-500 text-white" : "text-gray-400 hover:text-white hover:bg-gray-800"}`}
          title="大厅"
        >
          厅
        </button>
        <button
          onClick={() => setView("deck")}
          className={`w-10 h-10 rounded-xl text-xs font-bold transition-colors ${view === "deck" ? "bg-orange-500 text-white" : "text-gray-400 hover:text-white hover:bg-gray-800"}`}
          title="卡组"
        >
          组
        </button>
        <button
          onClick={() => setView("history")}
          className={`w-10 h-10 rounded-xl text-xs font-bold transition-colors ${view === "history" ? "bg-orange-500 text-white" : "text-gray-400 hover:text-white hover:bg-gray-800"}`}
          title="对局记录"
        >
          战
        </button>
        <div className="mt-auto">
          <NetStatePanel />
        </div>
      </nav>

      {/* 主内容区 */}
      <main className="relative flex-1 overflow-hidden">
        <OnlineCountBadge onClick={() => setShowPlayerList(true)} />
        {view === "lobby" && <LobbyPanel onGoToDeck={() => setView("deck")} />}
        {view === "deck" && <DeckChoosePanel onDeckSelected={() => setView("lobby")} />}
        {view === "history" && <HistoryPanel />}
      </main>

      <PlayerListPanel open={showPlayerList} onClose={() => setShowPlayerList(false)} />
      <InviteNotifyOverlay />
    </div>
  );
}

// opcgpro-vue/src/components/home/MainPanel.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useStore } from "@/composables/useStore";
import { useNetStore } from "@/store/netStore";
import { loadAllDecks } from "@/data/DeckMapper";
import Sidebar from "@/components/shared/Sidebar.vue";
import Ticks from "@/components/shared/Ticks.vue";
import LobbyPanel from "./LobbyPanel.vue";
import DeckChoosePanel from "./DeckChoosePanel.vue";
import HistoryPanel from "./HistoryPanel.vue";
import ChatPanel from "./ChatPanel.vue";
import PlayerListPanel from "./PlayerListPanel.vue";
import FriendlyRoomPanel from "./FriendlyRoomPanel.vue";
import InviteNotifyOverlay from "./InviteNotifyOverlay.vue";
import PlayerAvatar from "./PlayerAvatar.vue";
import NetStatePanel from "@/components/ui/NetStatePanel.vue";

const SELECTED_DECK_KEY = "grandumi_selected_deck";
const ONLINE_BADGE_POS_KEY = "grandumi_online_badge_pos";

type View = "lobby" | "deck" | "history";
const view = ref<View>("lobby");
const showPlayerList = ref(false);

const onlineCount = useStore(useNetStore, (s) => s.onlineCount);
const connState = useStore(useNetStore, (s) => s.connState);
const friendlyRoom = useStore(useNetStore, (s) => s.friendlyRoom);
const playerName = useStore(useNetStore, (s) => s.playerName);

const isConnected = () => connState.value === "connected";

onMounted(() => {
  const name = localStorage.getItem(SELECTED_DECK_KEY);
  if (!name) return;
  const saved = loadAllDecks()[name];
  if (!saved) return;
  useNetStore.getState().setSelectedDeck({
    name,
    leader: saved.leader,
    leaderName: saved.leaderName,
    cards: [saved.leader, ...saved.cards].join("\n"),
  });
});

// ── 在线人数徽标拖动 ──────────────────────────────────────────────────────
const badgePos = ref<{ x: number; y: number } | null>(null);
const badgeRef = ref<HTMLButtonElement | null>(null);
const drag = ref<{ startX: number; startY: number; baseX: number; baseY: number; moved: boolean } | null>(null);
const lastDragPos = ref<{ x: number; y: number } | null>(null);

onMounted(() => {
  try {
    const saved = localStorage.getItem(ONLINE_BADGE_POS_KEY);
    if (saved) badgePos.value = JSON.parse(saved);
  } catch {}
});

function onBadgePointerDown(e: PointerEvent) {
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
  drag.value = { startX: e.clientX, startY: e.clientY, baseX: rect.left, baseY: rect.top, moved: false };
  (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
}

function onBadgePointerMove(e: PointerEvent) {
  const d = drag.value;
  if (!d) return;
  const dx = e.clientX - d.startX;
  const dy = e.clientY - d.startY;
  if (!d.moved && Math.abs(dx) < 4 && Math.abs(dy) < 4) return;
  d.moved = true;
  const bw = (e.currentTarget as HTMLElement).offsetWidth;
  const bh = (e.currentTarget as HTMLElement).offsetHeight;
  const x = Math.min(Math.max(0, d.baseX + dx), window.innerWidth - bw);
  const y = Math.min(Math.max(0, d.baseY + dy), window.innerHeight - bh);
  badgePos.value = { x, y };
  lastDragPos.value = { x, y };
}

function onBadgePointerUp(e: PointerEvent) {
  const d = drag.value;
  drag.value = null;
  try { (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId); } catch {}
  if (!d) return;
  if (!d.moved) {
    showPlayerList.value = true;
  } else if (lastDragPos.value) {
    try { localStorage.setItem(ONLINE_BADGE_POS_KEY, JSON.stringify(lastDragPos.value)); } catch {}
  }
}

function onNavigate(v: View) {
  view.value = v;
}
</script>

<template>
  <template v-if="friendlyRoom">
    <FriendlyRoomPanel />
    <InviteNotifyOverlay />
  </template>

  <div v-else class="main-root">
    <!-- 顶部 TopBar 已由 App.vue 全局提供 -->

    <!-- 左侧 Sidebar -->
    <Sidebar
      :username="playerName || 'guest'"
      :active="view"
      :connected="isConnected()"
      @navigate="onNavigate"
    />

    <!-- 主内容区（左 116 + 右 0） -->
    <main class="main-content">
      <div class="main-content__inner">
        <!-- 在线浮标（可拖动） -->
        <button
          ref="badgeRef"
          type="button"
          title="查看在线玩家（可拖动）"
          :style="badgePos
            ? { position: 'fixed', left: `${badgePos.x}px`, top: `${badgePos.y}px` }
            : { position: 'fixed', right: '1.25rem', bottom: '4.5rem' }"
          class="online-badge"
          @pointerdown="onBadgePointerDown"
          @pointermove="onBadgePointerMove"
          @pointerup="onBadgePointerUp"
        >
          <span class="online-badge__dot" />
          <span class="online-badge__text">在线</span>
          <span class="online-badge__count">{{ onlineCount }}</span>
        </button>

        <Transition name="view-fade" mode="out-in">
          <!-- 大厅视图：双栏（中 Lobby + 右 Chat） -->
          <div v-if="view === 'lobby'" key="lobby" class="lobby-stack enter">
            <div class="lobby-stack__main">
              <LobbyPanel @go-to-deck="view = 'deck'" />
            </div>
            <aside class="lobby-stack__chat">
              <div class="panel lobby-chat-panel">
                <Ticks />
                <ChatPanel />
              </div>
            </aside>
          </div>

          <DeckChoosePanel
            v-else-if="view === 'deck'"
            key="deck"
            class="solo-panel enter"
            @deck-selected="view = 'lobby'"
          />
          <HistoryPanel v-else-if="view === 'history'" key="history" class="solo-panel enter" />
        </Transition>
      </div>
    </main>

    <PlayerListPanel :open="showPlayerList" @close="showPlayerList = false" />
    <InviteNotifyOverlay />
  </div>
</template>

<style scoped>
.main-root {
  position: relative;
  display: block;
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  background: transparent; /* 全局 AnimatedBackground 在 App.vue 根布局（z:0） */
  color: var(--ink);
  font-family: var(--font-ui);
}

/* ── 内容区：左 116(top:72 + 16 + width:84 + gap:16) 右 0 ── */
.main-content {
  position: absolute;
  top: 56px; /* 跳过 TopBar */
  left: 116px; /* 跳过 Sidebar(84 + left:16 + gap:16) */
  right: 0;
  bottom: 0;
  overflow: hidden;
}
.main-content__inner {
  position: absolute;
  inset: 0;
  display: flex;
}

/* ── 大厅双栏 ── */
.lobby-stack {
  flex: 1;
  display: flex;
  gap: 14px;
  padding: 14px 14px 14px 0;
  min-height: 0;
}
.lobby-stack__main {
  flex: 1;
  min-width: 0;
  overflow: auto;
  padding-top: 14px;
}
.lobby-stack__chat {
  width: 320px;
  flex-shrink: 0;
  padding: 14px 14px 14px 0;
}
.lobby-chat-panel {
  height: 100%;
  display: flex;
  flex-direction: column;
  padding: 0;
  overflow: hidden;
}

/* ── 单栏（卡组/战绩） ── */
.solo-panel {
  flex: 1;
  min-width: 0;
  overflow: hidden;
}

/* ── 在线浮标 ── */
.online-badge {
  z-index: 30;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.4rem 0.85rem;
  font-family: var(--font-mono);
  font-size: 0.7rem;
  letter-spacing: 0.15em;
  color: var(--ink);
  background: color-mix(in srgb, var(--bg0) 78%, transparent);
  border: 1px solid var(--line);
  border-radius: var(--radius-pill);
  backdrop-filter: blur(8px);
  cursor: grab;
  user-select: none;
  transition: all 200ms ease;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.4);
}
.online-badge:hover {
  border-color: var(--line-strong);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.4), 0 0 12px var(--primary-glow);
}
.online-badge:active {
  cursor: grabbing;
}
.online-badge__dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--primary);
  box-shadow: 0 0 6px var(--primary), 0 0 12px var(--primary-glow);
  animation: grandumi-dot-pulse 2s ease-in-out infinite;
}
.online-badge__text {
  color: var(--ink-dim);
  text-transform: uppercase;
}
.online-badge__count {
  color: var(--primary);
  font-weight: 700;
  text-shadow: 0 0 6px var(--primary-glow);
}

/* ── 视图切换动画 ── */
.view-fade-enter-active,
.view-fade-leave-active {
  transition: opacity 0.22s ease, transform 0.22s ease;
}
.view-fade-enter-from {
  opacity: 0;
  transform: translateX(12px);
}
.view-fade-leave-to {
  opacity: 0;
  transform: translateX(-12px);
}

/* ── 移动端：折叠 Sidebar ── */
@media (max-width: 900px) {
  .main-content { left: 0; top: 56px; }
  .lobby-stack__chat { display: none; }
}
</style>
